name: Build and Push Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Dockerイメージをビルド
      - name: Build Docker Image
        run: |
          docker build -t my-docker-image:latest .devcontainer

      # 必要に応じてGitHub Container Registryにログイン
      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Dockerイメージをプッシュ
      - name: Push Docker Image
        run: |
          docker tag my-docker-image:latest ghcr.io/${{ github.repository_owner }}/my-docker-image:latest
          docker push ghcr.io/${{ github.repository_owner }}/my-docker-image:latest

                # Dockerコンテナ内でFORDを実行してドキュメントを生成
      - name: Generate Documentation
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace my-docker-image:latest \
          zsh -c "cd /workspace && ford docs/api-docs-ford-settings.md"


                # 生成されたドキュメントをアーティファクトとしてアップロード
      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/api-docs
          if-no-files-found: error

      # リンク切れのチェック
      - name: Broken Link Check
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: technote-space/broken-link-checker-action@v1
        with:
          TARGET: file://${{ github.workspace }}/doc/api-docs/index.html
          RECURSIVE: true
          ASSIGNEES: ${{ github.actor }}

      # `gh-pages`ブランチにドキュメントをデプロイ
      - name: Deploy API Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: docs/api-docs
