#!/bin/zsh

set -e

# Use provided arguments or default to 'intel'
COMPILERS=("$@")
if [ ${#COMPILERS[@]} -eq 0 ]; then
    COMPILERS=("intel")
fi

ROOT_DIR=$(realpath .)
THIRD_PARTY_DIR="$ROOT_DIR/third_party"
IAPWS_DIR="$THIRD_PARTY_DIR/IAPWS"

mkdir -p "$THIRD_PARTY_DIR"
cd "$THIRD_PARTY_DIR"

# Clone IAPWS only once if it does not exist
if [ ! -d "$IAPWS_DIR" ]; then
    git clone https://github.com/ysy307/IAPWS.git "$IAPWS_DIR"
fi
cd "$IAPWS_DIR"

# Loop through each specified compiler
for COMPILER in "${COMPILERS[@]}"; do
    echo "--- Building IAPWS for $COMPILER ---"

    # Set preset names based on compiler selection
    case "$COMPILER" in
      intel)
        CONFIG_PRESET="intel-release"
        BUILD_PRESET="build-intel-release"
        ;;
      gnu)
        CONFIG_PRESET="gnu-release"
        BUILD_PRESET="build-gnu-release"
        ;;
      nvidia)
        CONFIG_PRESET="nvidia-release"
        BUILD_PRESET="build-nvidia-release"
        ;;
      *)
        echo "Error: Unknown compiler '$COMPILER'. Skipping."
        continue
        ;;
    esac

    INSTALL_PREFIX="$THIRD_PARTY_DIR/.local/$COMPILER"
    BUILD_DIR="build/${CONFIG_PRESET}"

    # Reset only the compiler-specific build directory generated by preset
    if [ -d "$BUILD_DIR" ]; then
        rm -rf "$BUILD_DIR"
    fi

    # Configure using preset
    cmake --preset="$CONFIG_PRESET" \
          -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
          -DCMAKE_VERBOSE_MAKEFILE=On

    # Build using preset
    cmake --build --preset="$BUILD_PRESET"

    # Install from preset build directory
    cmake --install "$BUILD_DIR" --prefix "$INSTALL_PREFIX"

    echo "--- Completed IAPWS for $COMPILER ---"
done