#:set VTYPES = [('dp', 'real(real64)', 'real64', '0.0d0', 'es16.8e3', 'Vector Size:'), ('int', 'integer(int32)', 'int32', '0', 'I12', 'Vector(Int) Size:')]
#:for VTYPE, FTYPE, KTYPE, ZERO, VALFMT, HDR in VTYPES
!>
!> Implements type_vector_${VTYPE}$ procedures.
!>
submodule(core_types_algebra_vector) algebra_vector_${VTYPE}$
    implicit none

contains

    module subroutine initialize_vector_${VTYPE}$(self, num_nodes, num_blocks)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        integer(int32), intent(in) :: num_nodes
        integer(int32), intent(in), optional :: num_blocks

        call deallocate_array(self%val)

        self%num_nodes = num_nodes
        self%num_blocks = optval(num_blocks, 1)

        call allocate_array(self%val, self%num_blocks * self%num_nodes)
        self%val = ${ZERO}$

        self%status = VECTOR_STATUS%SUCCESS
        self%is_initialized_vector = .true.
    end subroutine initialize_vector_${VTYPE}$

    module subroutine destroy_vector_${VTYPE}$(self)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self

        call deallocate_array(self%val)
        self%num_nodes = 0
        self%num_blocks = 0
        self%status = VECTOR_STATUS%SUCCESS
        self%is_initialized_vector = .false.
    end subroutine destroy_vector_${VTYPE}$

    module pure function is_initialized_vector_${VTYPE}$(self) result(initialized)
        implicit none
        class(type_vector_${VTYPE}$), intent(in) :: self
        logical :: initialized
        initialized = self%is_initialized_vector
    end function is_initialized_vector_${VTYPE}$

    module pure function get_size_vector_${VTYPE}$(self) result(vector_size)
        implicit none
        class(type_vector_${VTYPE}$), intent(in) :: self
        integer(int32) :: vector_size
        vector_size = self%num_nodes
    end function get_size_vector_${VTYPE}$

    module function get_data_vector_${VTYPE}$(self) result(data)
        implicit none
        class(type_vector_${VTYPE}$), intent(in), target :: self
        ${FTYPE}$, pointer, dimension(:) :: data

        if (allocated(self%val)) then
            data => self%val
        else
            nullify(data)
        end if
    end function get_data_vector_${VTYPE}$

    module pure function get_status_vector_${VTYPE}$(self) result(status)
        implicit none
        class(type_vector_${VTYPE}$), intent(in) :: self
        type(type_constant_id) :: status
        status = self%status
    end function get_status_vector_${VTYPE}$

    #:if VTYPE == 'dp'
    module subroutine set_scalar_vector_${VTYPE}$(self, op, scalar_value, row_block)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        type(type_constant_id), intent(in) :: op
        ${FTYPE}$, intent(in) :: scalar_value
        integer(int32), intent(in), optional :: row_block

        integer(int32) :: nb

        if (.not. VECTOR_OPS%is_valid(op)) then
            self%status = VECTOR_STATUS%ILL_OPERATIONS
            return
        end if
        nb = optval(row_block, 1)

        associate (val => self%val, n_blks => self%num_blocks)
            select case (op%ID)
            case (VECTOR_OPS%INS%ID)
                val(nb :: n_blks) = scalar_value
            case (VECTOR_OPS%ADD%ID)
                val(nb :: n_blks) = val(nb :: n_blks) + scalar_value
            case default
                self%status = VECTOR_STATUS%ILL_OPERATIONS
            end select
        end associate
    end subroutine set_scalar_vector_${VTYPE}$

    #:endif
    module subroutine set_array_vector_${VTYPE}$(self, op, array_value, row_block)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        type(type_constant_id), intent(in) :: op
        ${FTYPE}$, intent(in) :: array_value(:)
        integer(int32), intent(in), optional :: row_block

        integer(int32) :: nb

        if (.not. VECTOR_OPS%is_valid(op)) then
            self%status = VECTOR_STATUS%ILL_OPERATIONS
            return
        end if
        nb = optval(row_block, 1)

        if (.not. value_in_range(nb, 1_int32, self%num_blocks)) then
            self%status = VECTOR_STATUS%OUT_OF_MEMORY
            return
        end if

        if (size(array_value) /= self%num_nodes) then
            self%status = VECTOR_STATUS%ILL_OPERATIONS
            return
        end if

        associate (val => self%val, n_blks => self%num_blocks)
            select case (op%ID)
            case (VECTOR_OPS%INS%ID)
                val(nb :: n_blks) = array_value
            case (VECTOR_OPS%ADD%ID)
                val(nb :: n_blks) = val(nb :: n_blks) + array_value
            case default
                self%status = VECTOR_STATUS%ILL_OPERATIONS
            end select
        end associate
    end subroutine set_array_vector_${VTYPE}$

    module subroutine set_value_at_index_vector_${VTYPE}$(self, op, global_index, value, row_block)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        type(type_constant_id), intent(in) :: op
        integer(int32), intent(in) :: global_index
        ${FTYPE}$, intent(in) :: value
        integer(int32), intent(in), optional :: row_block

        integer(int32) :: nb, idx

        if (.not. VECTOR_OPS%is_valid(op)) then
            self%status = VECTOR_STATUS%ILL_OPERATIONS
            return
        end if
        nb = optval(row_block, 1)
        idx = (global_index - 1) * self%num_blocks + nb

        select case (op%ID)
        case (VECTOR_OPS%INS%ID)
            self%val(idx) = value
        case (VECTOR_OPS%ADD%ID)
            self%val(idx) = self%val(idx) + value
        case default
            self%status = VECTOR_STATUS%ILL_OPERATIONS
        end select
    end subroutine set_value_at_index_vector_${VTYPE}$

    module subroutine set_values_at_indices_vector_${VTYPE}$(self, op, global_indices, new_values, row_block)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        type(type_constant_id), intent(in) :: op
        integer(int32), intent(in) :: global_indices(:)
        ${FTYPE}$, intent(in) :: new_values(:)
        integer(int32), intent(in), optional :: row_block

        integer(int32) :: nb
        integer(int32), allocatable :: target_indices(:)

        if (.not. VECTOR_OPS%is_valid(op)) then
            self%status = VECTOR_STATUS%ILL_OPERATIONS
            return
        end if
        nb = optval(row_block, 1)

        call allocate_array(target_indices, size(global_indices))
        target_indices = (global_indices - 1) * self%num_blocks + nb

        select case (op%ID)
        case (VECTOR_OPS%INS%ID)
            self%val(target_indices) = new_values
        case (VECTOR_OPS%ADD%ID)
            self%val(target_indices) = self%val(target_indices) + new_values
        case default
            self%status = VECTOR_STATUS%ILL_OPERATIONS
        end select
    end subroutine set_values_at_indices_vector_${VTYPE}$

    module subroutine scale_vector_${VTYPE}$(self, op, alpha)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        type(type_constant_id), intent(in) :: op
        class(type_vector_${VTYPE}$), intent(in) :: alpha

        ${FTYPE}$, pointer :: alpha_data(:)

        if (.not. VECTOR_OPS%is_valid(op)) then
            self%status = VECTOR_STATUS%ILL_OPERATIONS
            return
        end if
        alpha_data => alpha%get_data()

        select case (op%ID)
        case (VECTOR_OPS%SCALE_SYMM_DIAG%ID, VECTOR_OPS%SCALE_JACOBI%ID)
            #:if VTYPE == 'dp'
            self%val = self%val * alpha_data
            #:else
            if (size(alpha_data) /= self%num_nodes) self%status = VECTOR_STATUS%ILL_OPERATIONS
            #:endif
        case default
            self%status = VECTOR_STATUS%ILL_OPERATIONS
        end select
    end subroutine scale_vector_${VTYPE}$

    module subroutine copy_vector_${VTYPE}$(self, source_vector)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        class(type_vector_${VTYPE}$), intent(in) :: source_vector

        if (self%is_initialized_vector .and. &
            self%num_nodes == source_vector%num_nodes .and. &
            self%num_blocks == source_vector%num_blocks) then
            self%val = source_vector%val
        else
            if (self%is_initialized_vector) call self%destroy()
            call self%initialize(source_vector%num_nodes, source_vector%num_blocks)
            self%val = source_vector%val
        end if

        self%status = VECTOR_STATUS%SUCCESS
    end subroutine copy_vector_${VTYPE}$

    module subroutine zero_vector_${VTYPE}$(self)
        implicit none
        class(type_vector_${VTYPE}$), intent(inout) :: self
        self%val = ${ZERO}$
    end subroutine zero_vector_${VTYPE}$

    module subroutine display_vector_${VTYPE}$(self, unit_in)
        implicit none
        class(type_vector_${VTYPE}$), intent(in) :: self
        integer(int32), intent(in), optional :: unit_in

        integer(int32) :: i, b, idx, unit

        unit = optval(unit_in, output_unit)

        if (.not. self%is_initialized_vector) then
            write (unit, '(a)') "Vector not initialized."
            return
        end if

        write (unit, '(a,i0,a,i0)') "${HDR}$", self%num_nodes, " Blocks:", self%num_blocks
        do i = 1, self%num_nodes
            do b = 1, self%num_blocks
                idx = (i - 1) * self%num_blocks + b
                write (unit, '(A,I0,A,I0,A,${VALFMT}$)') "Node ", i, " Block ", b, ": ", self%val(idx)
            end do
        end do
    end subroutine display_vector_${VTYPE}$

    module subroutine check_vector_${VTYPE}$(self)
        implicit none
        class(type_vector_${VTYPE}$), intent(in) :: self

        if (.not. self%is_initialized_vector) then
            write (*, *) "Error: Vector not initialized."
            return
        end if

        select case (self%status%ID)
        case (VECTOR_STATUS%SUCCESS%ID)
            return
        case (VECTOR_STATUS%OUT_OF_MEMORY%ID)
            write (*, *) "Error: Vector operation failed due to out of memory."
        case (VECTOR_STATUS%ILL_OPERATIONS%ID)
            write (*, *) "Error: Vector operation failed due to illegal operation."
        case (VECTOR_STATUS%NOT_IMPLEMENTED%ID)
            write (*, *) "Error: Vector operation not implemented."
        case default
            write (*, *) "Error: Vector operation failed due to unknown error."
        end select
    end subroutine check_vector_${VTYPE}$

end submodule algebra_vector_${VTYPE}$

#:endfor
