Allocate_DF – FTDSS
Allocate_DF Subroutine
11 statements
Source File
public subroutine Allocate_DF(ar_DF, n)
Arguments
Type Intent Optional Attributes Name
type(DF), intent(inout) :: ar_DF
integer(kind=int32), intent(in) :: n
Calls
Called by
Contents
Source Code
Allocate_DF
Source Code
    subroutine Allocate_DF(ar_DF, n)
        implicit none
        type(DF), intent(inout) :: ar_DF
        integer(int32), intent(in) :: n
        call Allocate_Vector(ar_DF%old, n)
        call Allocate_Vector(ar_DF%pre, n)
        call Allocate_Vector(ar_DF%new, n)
        call Allocate_Vector(ar_DF%dif, n)
        call Allocate_Vector(ar_DF%div, n)
        call Allocate_Vector(ar_DF%tmp, n)
    end subroutine Allocate_DF
Call graph
allocate_df calls allocate_vector
allocate_vector calls check_allocate_rank1_int32, check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32_specify, check_allocate_rank1_real64
check_allocate_rank1_int32 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
error_message calls mpi_finalize
allocate_solver calls allocate_df