Allocate_BCinfo – FTDSS
Allocate_BCinfo Subroutine
15 statements
Source File
public subroutine Allocate_BCinfo(BCinfo, nNode, nType, nEdge)
Arguments
Type Intent Optional Attributes Name
type(BoudaryConditionInfo), intent(inout) :: BCinfo
integer(kind=int32), intent(in) :: nNode
integer(kind=int32), intent(in) :: nType
integer(kind=int32), intent(in), optional :: nEdge
Calls
Contents
Source Code
Allocate_BCinfo
Source Code
    subroutine Allocate_BCinfo(BCinfo, nNode, nType, nEdge)
        implicit none
        type(BoudaryConditionInfo), intent(inout) :: BCinfo
        integer(int32), intent(in) :: nNode, nType
        integer(int32), intent(in), optional :: nEdge
        call Allocate_Vector(BCinfo%Node, nNode)
        call Allocate_Vector(BCinfo%TypeKey, nNode)
        call Allocate_Vector(BCinfo%type, nType)
        call Allocate_Vector(BCinfo%value, nType)
        if (present(nEdge)) then
            ! print*, nEdge
            call Allocate_INT2d(BCinfo%Edges, nEdge)
            call Allocate_Vector(BCinfo%EdgesDirection, nEdge)
            call Allocate_Vector(BCinfo%EdgesDistance, nEdge)
        end if
    end subroutine Allocate_BCinfo
Call graph
allocate_bcinfo calls allocate_vector, allocate_int2d
allocate_vector calls check_allocate_rank1_int32_specify, check_allocate_rank1_real64, check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32
allocate_int2d calls allocate_vector
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
error_message calls mpi_finalize