Allocate_DP2d – FTDSS
Allocate_DP2d Subroutine
7 statements
Source File
public subroutine Allocate_DP2d(ar_DP2d, n)
Arguments
Type Intent Optional Attributes Name
type(DP2d), intent(inout) :: ar_DP2d
integer(kind=int32), intent(in) :: n
Calls
Called by
Contents
Source Code
Allocate_DP2d
Source Code
    subroutine Allocate_DP2d(ar_DP2d, n)
        implicit none
        type(DP2d), intent(inout) :: ar_DP2d
        integer(int32), intent(in) :: n
        call Allocate_Vector(ar_DP2d%x, n)
        call Allocate_Vector(ar_DP2d%y, n)
    end subroutine Allocate_DP2d
Call graph
allocate_dp2d calls allocate_vector
allocate_vector calls check_allocate_rank1_int32, check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32_specify, check_allocate_rank1_real64
check_allocate_rank1_int32 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
error_message calls mpi_finalize
allocate_solver calls allocate_dp2d