Allocate_Solver – FTDSS
Allocate_Solver Subroutine
39 statements
Source File
public subroutine Allocate_Solver(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Contents
Source Code
Allocate_Solver
Source Code
    subroutine Allocate_Solver(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        !* Allocate Geometry2d
        call Allocate_Matrix(Solver%N%pElement, Solver%N%shape, Solver%N%element)
        call Allocate_Vector(Solver%N%vCood%x, Solver%N%node)
        call Allocate_Vector(Solver%N%vCood%y, Solver%N%node)
        call Allocate_Vector(Solver%N%eArea, Solver%N%element)
        call Allocate_Matrix(Solver%N%Basis%a, Solver%N%ShCoe, Solver%N%element)
        call Allocate_Matrix(Solver%N%Basis%b, Solver%N%ShCoe, Solver%N%element)
        call Allocate_Matrix(Solver%N%Basis%c, Solver%N%ShCoe, Solver%N%element)
        if (Solver%N%ShCoe == 4) call Allocate_Matrix(Solver%N%Basis%d, Solver%N%ShCoe, Solver%N%element)
        call Allocate_Vector(Solver%mWater%old, Solver%N%node)
        call Allocate_Vector(Solver%mWater%pre, Solver%N%node)
        call Allocate_Vector(Solver%mIce%old, Solver%N%node)
        call Allocate_Vector(Solver%mIce%pre, Solver%N%node)
        call Allocate_Vector(Solver%mIce%dif, Solver%N%node)
        call Allocate_DF(Solver%Si, Solver%N%node)
        if (Solver%isHeat) then
            call Allocate_DF(Solver%Heat%Variables%Cs, Solver%N%node)
            call Allocate_DF(Solver%Heat%Variables%Cp, Solver%N%node)
            call Allocate_DF(Solver%Heat%Variables%lambda, Solver%N%node)
            call Allocate_DF(Solver%Heat%Variables%rho, Solver%N%node)
            call Allocate_DF(Solver%Heat%Variables%Ca, Solver%N%node)
            call Allocate_DF(Solver%T, Solver%N%node)
            call Allocate_Vector(Solver%Heat%Rhs, Solver%N%node)
            call Allocate_Vector(Solver%Heat%Variables%Phase, Solver%N%node)
            call Allocate_Matrix(Solver%Heat%RA, Solver%N%node, Solver%N%node)
            call Allocate_DP2d(Solver%Heat%Variables%Tgrad, Solver%N%node)
            call Allocate_DP2d(Solver%Heat%Variables%TFlux, Solver%N%node)
        end if
        if (Solver%isWater) then
            call Allocate_DF(Solver%Water%Variables%Klh, Solver%N%node)
            call Allocate_DP2d(Solver%Water%Variables%wFlux, Solver%N%node)
            call Allocate_DP2d(Solver%Water%Variables%hGrad, Solver%N%node)
            call Allocate_DF(Solver%P, Solver%N%node)
            call Allocate_Vector(Solver%Water%Rhs, Solver%N%node)
            call Allocate_Matrix(Solver%Water%RA, Solver%N%node, Solver%N%node)
        end if
    end subroutine Allocate_Solver
Call graph
allocate_solver calls allocate_matrix, allocate_df, allocate_vector, allocate_dp2d
allocate_matrix calls check_allocate_rank2_int32, check_allocate_rank2_real64
allocate_df calls allocate_vector
allocate_vector calls check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32, check_allocate_rank1_int32_specify, check_allocate_rank1_real64
allocate_dp2d calls allocate_vector
check_allocate_rank2_int32 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank2_real64 calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
error_message calls mpi_finalize