Assemble_GM_Heat_IC – FTDSS
Assemble_GM_Heat_IC Subroutine
20 statements
Source File
public subroutine Assemble_GM_Heat_IC(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Called by
Contents
Source Code
Assemble_GM_Heat_IC
Source Code
    subroutine Assemble_GM_Heat_IC(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        ! if (.not. Solver%isWater) then
            if (Solver%Flags%isTRM) then
                call Calc_GM_Time_TRM(Solver)
                call Calc_GM_Diffusion_TRM(Solver)
                call SpMV(tmpCRS1, Solver%T%old(:), Solver%Heat%Rhs(:))
                Solver%Heat%LHS_A%val(:) = Solver%Heat%LHS_A%val(:) + tmpCRS1%val(:)
            else if (Solver%Flags%isGCC) then
                call Calc_GM_Time_Divide(Solver)
                call Calc_GM_Diffusion(Solver)
                call SpMV(tmpCRS2, Solver%T%old(:), Solver%Heat%Rhs(:))
                Solver%Heat%LHS_A%val(:) = Solver%Heat%LHS_A%val(:) + tmpCRS1%val(:)
            else if (Solver%Flags%isPower) then
                call Calc_GM_Time_Divide(Solver)
                call Calc_GM_Diffusion(Solver)
                call SpMV(tmpCRS2, Solver%T%old(:), Solver%Heat%Rhs(:))
                Solver%Heat%LHS_A%val(:) = Solver%Heat%LHS_A%val(:) + tmpCRS1%val(:)
            end if
        ! end if
    end subroutine Assemble_GM_Heat_IC
Call graph
assemble_gm_heat_ic calls calc_gm_time_trm, calc_gm_diffusion, matrix_vector_product_crs, calc_gm_diffusion_trm, calc_gm_time_divide
calc_gm_time_trm calls find_crs_indexes
calc_gm_diffusion calls find_crs_indexes
calc_gm_diffusion_trm calls find_crs_indexes
calc_gm_time_divide calls find_crs_indexes, set_c
find_crs_indexes calls find_crs_index
fix_initialcondition_gradient_heat calls assemble_gm_heat_ic
fix_initialcondition calls fix_initialcondition_gradient_heat