Assemble_GM_Heat – FTDSS
Assemble_GM_Heat Subroutine
29 statements
Source File
public subroutine Assemble_GM_Heat(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Contents
Source Code
Assemble_GM_Heat
Source Code
    subroutine Assemble_GM_Heat(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        if (.not. Solver%isWater) then
            if (Solver%Flags%isTRM) then
                call Calc_GM_Time_TRM(Solver)
                call Calc_GM_Diffusion_TRM(Solver)
                call SpMV(tmpCRS1, Solver%T%old(:), Solver%Heat%Rhs(:))
                Solver%Heat%LHS_A%val(:) = Solver%Heat%LHS_A%val(:) + tmpCRS1%val(:)
            else if (Solver%Flags%isGCC .or. Solver%Flags%isPower) then
                call Calc_GM_Time_Divide(Solver)
                call Calc_GM_Diffusion(Solver)
                call SpMV(tmpCRS2, Solver%T%old(:), Solver%Heat%Rhs(:))
                Solver%Heat%LHS_A%val(:) = Solver%Heat%LHS_A%val(:) + tmpCRS1%val(:)
            end if
        else
            if (Solver%Flags%isTRM) then
                call Calc_GM_Time_TRM(Solver)
                ! call Calc_GM_Time_TRM_F(Solver)
                call Calc_GM_Diffusion_Advection_TRM(Solver)
                ! call Calc_GM_Diffusion_TRM(Solver)
                call SpMV(tmpCRS1, Solver%T%old(:), Solver%Heat%Rhs(:))
                ! print*,Solver%Heat%Rhs(:)
                ! stop
                ! Solver%Heat%RA(:,:) = Solver%Heat%RA(:,:) + tmpA(:,:)
                Solver%Heat%LHS_A%val(:) = Solver%Heat%LHS_A%val(:) + tmpCRS1%val(:)
            else if (Solver%Flags%isGCC .or. Solver%Flags%isPower) then
                call Calc_GM_Time_Divide(Solver)
                call Calc_GM_Diffusion_Advection(Solver)
                call SpMV(tmpCRS2, Solver%T%old(:), Solver%Heat%Rhs(:))
                Solver%Heat%LHS_A%val(:) = Solver%Heat%LHS_A%val(:) + tmpCRS1%val(:)
            end if
        end if
    end subroutine Assemble_GM_Heat
Call graph
assemble_gm_heat calls calc_gm_time_trm, calc_gm_diffusion, matrix_vector_product_crs, calc_gm_diffusion_trm, calc_gm_time_divide, calc_gm_diffusion_advection_trm, calc_gm_diffusion_advection
calc_gm_time_trm calls find_crs_indexes
calc_gm_diffusion calls find_crs_indexes
calc_gm_diffusion_trm calls find_crs_indexes
calc_gm_time_divide calls find_crs_indexes, set_c
calc_gm_diffusion_advection_trm calls find_crs_indexes
calc_gm_diffusion_advection calls find_crs_indexes
find_crs_indexes calls find_crs_index