Calc_GM_Time_TRM – FTDSS
Calc_GM_Time_TRM Subroutine
27 statements
Source File
private subroutine Calc_GM_Time_TRM(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Called by
Contents
Source Code
Calc_GM_Time_TRM
Source Code
    subroutine Calc_GM_Time_TRM(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        integer(int32)                  :: iN, p1, p2, p3
        integer(int32)                  :: indexes(Solver%N%Shcoe ** 2)
        real(real64)                    :: CoeA, C1, C2, C3, C
        tmpCRS1%val(:) = 0.0d0
        do iN = 1, Solver%N%element
            p1   = Solver%N%pElement(1, iN)
            p2   = Solver%N%pElement(2, iN)
            p3   = Solver%N%pElement(3, iN)
            CoeA = Solver%N%eArea(iN) * D12 / Solver%Time%dt
            C1   = Solver%Heat%Variables%Cp%pre(p1)
            C2   = Solver%Heat%Variables%Cp%pre(p2)
            C3   = Solver%Heat%Variables%Cp%pre(p3)
            call Find_CRS_Indexes(udmp, tmpCRS1, p1, p2, p3, indexes(:))
            tmpCRS1%Val(indexes(1)) = tmpCRS1%Val(indexes(1)) + CoeA * C1 * 2.d0
            tmpCRS1%Val(indexes(2)) = tmpCRS1%Val(indexes(2)) + CoeA * C1
            tmpCRS1%Val(indexes(3)) = tmpCRS1%Val(indexes(3)) + CoeA * C1
            tmpCRS1%Val(indexes(4)) = tmpCRS1%Val(indexes(4)) + CoeA * C2
            tmpCRS1%Val(indexes(5)) = tmpCRS1%Val(indexes(5)) + CoeA * C2 * 2.d0
            tmpCRS1%Val(indexes(6)) = tmpCRS1%Val(indexes(6)) + CoeA * C2
            tmpCRS1%Val(indexes(7)) = tmpCRS1%Val(indexes(7)) + CoeA * C3
            tmpCRS1%Val(indexes(8)) = tmpCRS1%Val(indexes(8)) + CoeA * C3
            tmpCRS1%Val(indexes(9)) = tmpCRS1%Val(indexes(9)) + CoeA * C3 * 2.d0
        end do
    end subroutine Calc_GM_Time_TRM
Call graph
calc_gm_time_trm calls find_crs_indexes
find_crs_indexes calls find_crs_index
assemble_gm_heat calls calc_gm_time_trm
assemble_gm_heat_ic calls calc_gm_time_trm
fix_initialcondition_gradient_heat calls assemble_gm_heat_ic
fix_initialcondition calls fix_initialcondition_gradient_heat