Calc_Area_31 – FTDSS
Calc_Area_31 Subroutine
14 statements
Source File
public subroutine Calc_Area_31(Geometry)
Arguments
Type Intent Optional Attributes Name
type(Geometry2d), intent(inout) :: Geometry
Calls
Called by
Contents
Source Code
Calc_Area_31
Source Code
    subroutine Calc_Area_31(Geometry)
        implicit none
        type(Geometry2d), intent(inout) :: Geometry
        type(Vector2d)                  :: p1, p2, p3
        integer(int32)                  :: elem
        do elem = 1, Geometry%element
            call set_point(Geometry, elem, p1, p2, p3)
            if (elem < 1 .or. elem > Geometry%element) then
                call error_message(932)
            else
                Geometry%eArea(elem) = abs((p2%x - p1%x) * (p3%y - p1%y) - (p2%y - p1%y) * (p3%x - p1%x)) / 2.d0
            end if
        end do
    end subroutine Calc_Area_31
Call graph
calc_area_31 calls set_point, error_message
set_point calls set_point_31
error_message calls mpi_finalize
set_point_31 calls error_message
calc_area calls calc_area_31