Calc_GM_Time_Divide – FTDSS
Calc_GM_Time_Divide Subroutine
25 statements
Source File
private subroutine Calc_GM_Time_Divide(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Called by
Contents
Source Code
Calc_GM_Time_Divide
Source Code
    subroutine Calc_GM_Time_Divide(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        integer(int32)                  :: iN, p1, p2, p3
        integer(int32)                  :: indexes(Solver%N%Shcoe)
        real(real64)                     :: CoeA, C11, C12, C13, C21, C22, C23
        tmpCRS1%val(:) = 0.0d0
        tmpCRS2%val(:) = 0.0d0
        do iN =1, Solver%N%element
            p1   = Solver%N%pElement(1, iN)
            p2   = Solver%N%pElement(2, iN)
            p3   = Solver%N%pElement(3, iN)
            CoeA = Solver%N%eArea(iN) * D3 / Solver%Time%dt
            call Set_C(Solver%Heat%Variables%Ca, Solver%Heat%Variables%Phase(p1), p1, C11, C21)
            call Set_C(Solver%Heat%Variables%Ca, Solver%Heat%Variables%Phase(p2), p2, C12, C22)
            call Set_C(Solver%Heat%Variables%Ca, Solver%Heat%Variables%Phase(p3), p3, C13, C23)
            call Find_CRS_Indexes(dmp, tmpCRS1, p1, p2, p3, indexes(:))
            tmpCRS1%Val(indexes(1)) = tmpCRS1%Val(indexes(1)) + CoeA * C11
            tmpCRS1%Val(indexes(2)) = tmpCRS1%Val(indexes(2)) + CoeA * C12
            tmpCRS1%Val(indexes(3)) = tmpCRS1%Val(indexes(3)) + CoeA * C13
            tmpCRS2%Val(indexes(1)) = tmpCRS2%Val(indexes(1)) + CoeA * C21
            tmpCRS2%Val(indexes(2)) = tmpCRS2%Val(indexes(2)) + CoeA * C22
            tmpCRS2%Val(indexes(3)) = tmpCRS2%Val(indexes(3)) + CoeA * C23
        end do
    end subroutine Calc_GM_Time_Divide
Call graph
calc_gm_time_divide calls set_c, find_crs_indexes
find_crs_indexes calls find_crs_index
assemble_gm_heat calls calc_gm_time_divide
assemble_gm_heat_ic calls calc_gm_time_divide
fix_initialcondition_gradient_heat calls assemble_gm_heat_ic
fix_initialcondition calls fix_initialcondition_gradient_heat