Calc_GM_Diffusion_Richards_F – FTDSS
Calc_GM_Diffusion_Richards_F Subroutine
32 statements
Source File
private subroutine Calc_GM_Diffusion_Richards_F(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Called by
Contents
Source Code
Calc_GM_Diffusion_Richards_F
Source Code
    subroutine Calc_GM_Diffusion_Richards_F(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        integer(int32)                  :: iN, p1, p2, p3
        real(real64)                    :: CoeA, be1, be2, be3, ga1, ga2, ga3, K1, K2, K3, K
        Solver%Water%RA(:,:) = 0.0d0
        do iN =1, Solver%N%element
            p1   = Solver%N%pElement(1, iN)
            p2   = Solver%N%pElement(2, iN)
            p3   = Solver%N%pElement(3, iN)
            CoeA = D4 / Solver%N%eArea(iN)
            K1  = Solver%Water%Variables%Klh%pre(p1)
            K2  = Solver%Water%Variables%Klh%pre(p2)
            K3  = Solver%Water%Variables%Klh%pre(p3)
            K   = (K1 * K2 * K3) ** D3
            be1  = Solver%N%Basis%b(1, iN)
            be2  = Solver%N%Basis%b(2, iN)
            be3  = Solver%N%Basis%b(3, iN)
            ga1  = Solver%N%Basis%c(1, iN)
            ga2  = Solver%N%Basis%c(2, iN)
            ga3  = Solver%N%Basis%c(3, iN)
            Solver%Water%RA(p1, p1) = Solver%Water%RA(p1, p1) + K * (be1 * be1 + ga1 * ga1) * CoeA
            Solver%Water%RA(p1, p2) = Solver%Water%RA(p1, p2) + K * (be1 * be2 + ga1 * ga2) * CoeA
            Solver%Water%RA(p1, p3) = Solver%Water%RA(p1, p3) + K * (be1 * be3 + ga1 * ga3) * CoeA
            Solver%Water%RA(p2, p1) = Solver%Water%RA(p2, p1) + K * (be2 * be1 + ga2 * ga1) * CoeA
            Solver%Water%RA(p2, p2) = Solver%Water%RA(p2, p2) + K * (be2 * be2 + ga2 * ga2) * CoeA
            Solver%Water%RA(p2, p3) = Solver%Water%RA(p2, p3) + K * (be2 * be3 + ga2 * ga3) * CoeA
            Solver%Water%RA(p3, p1) = Solver%Water%RA(p3, p1) + K * (be3 * be1 + ga3 * ga1) * CoeA
            Solver%Water%RA(p3, p2) = Solver%Water%RA(p3, p2) + K * (be3 * be2 + ga3 * ga2) * CoeA
            Solver%Water%RA(p3, p3) = Solver%Water%RA(p3, p3) + K * (be3 * be3 + ga3 * ga3) * CoeA
        end do
    end subroutine Calc_GM_Diffusion_Richards_F
Call graph
assemble_gm_water calls calc_gm_diffusion_richards_f
assemble_gm_water_ic calls calc_gm_diffusion_richards_f
fix_initialcondition_gradient_water calls assemble_gm_water_ic
fix_initialcondition calls fix_initialcondition_gradient_water