Check_Allocate_rank1_int32 – FTDSS
Check_Allocate_rank1_int32 Subroutine
11 statements
Source File
private subroutine Check_Allocate_rank1_int32(iar, ar_size)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout), allocatable :: iar(:)
integer(kind=int32), intent(in) :: ar_size
Calls
Called by
Contents
Source Code
Check_Allocate_rank1_int32
Source Code
    subroutine Check_Allocate_rank1_int32(iar, ar_size)
        implicit none
        integer(int32), intent(in)                 :: ar_size
        integer(int32), intent(inout), allocatable :: iar(:)
        if (ar_size <= 0) call error_message(951)
        if (.not. allocated(iar)) then
            allocate(iar(ar_size))
        else
            call error_message(953)
        end if
    end subroutine Check_Allocate_rank1_int32
Call graph
check_allocate_rank1_int32 calls error_message
error_message calls mpi_finalize
allocate_vector calls check_allocate_rank1_int32
convert_crs calls allocate_vector
allocate_df calls allocate_vector
set_obs_coo_31 calls allocate_vector
allocate_int2d calls allocate_vector
set_boundary_condition_infomations calls allocate_vector
allocate_solver calls allocate_vector, allocate_df, allocate_dp2d
output_constructor calls allocate_vector
allocate_dp2d calls allocate_vector
allocate_bcinfo calls allocate_vector, allocate_int2d
set_obs_coo calls set_obs_coo_31
output calls output_constructor
heat_constructor calls set_boundary_condition_infomations
heat calls heat_constructor