Check_Allocate_rank2_int32 – FTDSS
Check_Allocate_rank2_int32 Subroutine
11 statements
Source File
private subroutine Check_Allocate_rank2_int32(imt, mt_size_1, mt_size_2)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout), allocatable :: imt(:,:)
integer(kind=int32), intent(in) :: mt_size_1
integer(kind=int32), intent(in) :: mt_size_2
Calls
Called by
Contents
Source Code
Check_Allocate_rank2_int32
Source Code
    subroutine Check_Allocate_rank2_int32(imt, mt_size_1, mt_size_2)
        implicit none
        integer(int32), intent(in)                 :: mt_size_1, mt_size_2
        integer(int32), intent(inout), allocatable :: imt(:,:)
        if (mt_size_1 <= 0 .or. mt_size_2 <= 0) call error_message(952)
        if (.not. allocated(imt)) then
            allocate(imt(mt_size_1, mt_size_2))
        else
            call error_message(954)
        end if
    end subroutine Check_Allocate_rank2_int32
Call graph
check_allocate_rank2_int32 calls error_message
error_message calls mpi_finalize
allocate_matrix calls check_allocate_rank2_int32
calc_gm_time_trm_f calls allocate_matrix
allocate_solver calls allocate_matrix
solve_initialize_bicgstab calls allocate_matrix
set_obs_coo_31 calls allocate_matrix
ils calls solve_initialize_bicgstab
set_obs_coo calls set_obs_coo_31