Check_Allocate_rank1_logical – FTDSS
Check_Allocate_rank1_logical Subroutine
11 statements
Source File
private subroutine Check_Allocate_rank1_logical(lar, ar_size)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), allocatable :: lar(:)
integer(kind=int32), intent(in) :: ar_size
Calls
Called by
Contents
Source Code
Check_Allocate_rank1_logical
Source Code
    subroutine Check_Allocate_rank1_logical(lar, ar_size)
        implicit none
        integer(int32), intent(in)                 :: ar_size
        logical,        intent(inout), allocatable :: lar(:)
        if (ar_size <= 0) call error_message(951)
        if (.not. allocated(lar)) then
            allocate(lar(ar_size))
        else
            call error_message(953)
        end if
    end subroutine Check_Allocate_rank1_logical
Call graph
check_allocate_rank1_logical calls error_message
error_message calls mpi_finalize
allocate_vector calls check_allocate_rank1_logical
output_constructor calls allocate_vector
allocate_bcinfo calls allocate_vector, allocate_int2d
allocate_dp2d calls allocate_vector
allocate_df calls allocate_vector
convert_crs calls allocate_vector
set_obs_coo_31 calls allocate_vector
set_boundary_condition_infomations calls allocate_vector
allocate_int2d calls allocate_vector
allocate_solver calls allocate_vector, allocate_dp2d, allocate_df
output calls output_constructor
heat_constructor calls set_boundary_condition_infomations
set_obs_coo calls set_obs_coo_31
heat calls heat_constructor