error_message – FTDSS
error_message Subroutine
93 statements
Source File
public subroutine error_message(err_number, myrank, opt, opt_file_name, copt1, copt2)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: err_number
integer(kind=int32), intent(in), optional :: myrank
real(kind=real64), intent(in), optional :: opt
character, intent(in), optional :: opt_file_name
character, intent(in), optional :: copt1
character, intent(in), optional :: copt2
Calls
Called by
Contents
Source Code
error_message
Source Code
    subroutine error_message(err_number, myrank, opt, opt_file_name, copt1, copt2)
        implicit none
        integer(int32), intent(in) :: err_number
        real(real64), optional, intent(in) :: opt
        integer(int32), optional, intent(in) :: myrank
        character(256) :: msg
        character(*), optional, intent(in) :: opt_file_name, copt1, copt2
        integer(int32) :: ierr
        if (err_number == 901) then
            write (msg, '(3a)') "Error: Does not exit file '", trim(adjustl(opt_file_name)), "'."
        else if (err_number == 902) then
            write (msg, '(3a)') "Error: Can not open file '", trim(adjustl(opt_file_name)), "'."
        else if (err_number == 903) then
            write (msg, '(3a)') "Error: Selected ", trim(adjustl(copt1)), " number is invalid."
        else if (err_number == 904) then
            msg = "Error: Opening file 'coordinate.in'"
        else if (err_number == 905) then
            msg = "Error: Opening file 'top.in'"
        else if (err_number == 906) then
            msg = "Error: Opening file 'coordinate.in'"
        else if (err_number == 911) then
            msg = "Error: The number of elements must be positive."
        else if (err_number == 912) then
            msg = "Error: The number of nodal must be positive."
        else if (err_number == 913) then
            msg = "Error: The number of shape must be positive."
        else if (err_number == 914) then
            msg = "Error: The number of dimention must be positive."
        else if (err_number == 915) then
            msg = "Error: Dirichlet boundary conditions for water transport must be positive."
        else if (err_number == 916) then
            msg = "Error: Dirichlet boundary conditions for heat transport must be positive."
        else if (err_number == 917) then
            msg = "Error: The value of porosity must be positive."
        else if (err_number == 918) then
            msg = "Error: The value of density must be positive."
        else if (err_number == 919) then
            msg = "Error: The value of hydrulic conductivity must be positive."
        else if (err_number == 920) then
            msg = "Error: The value of thermal conductivity must be positive."
        else if (err_number == 921) then
            msg = "Error: The value of specific heat must be positive."
        else if (err_number == 922) then
            msg = "Error: The value of latent heat must be positive."
        else if (err_number == 923) then
            msg = "Error: The number of concering time information must be positive."
        else if (err_number == 924) then
            msg = "Error: The initial and coolant temperature are same."
        else if (err_number == 928) then
            msg = "Error: Two or more points are the same."
        else if (err_number == 929) then
            msg = "Error: The number of array elements must be positive."
        else if (err_number == 930) then
            msg = "Error: The number of matrix elements must be positive."
        else if (err_number == 931) then
            msg = "Error: opening output file"
        else if (err_number == 932) then
            msg = "Error: Invalid element index"
        else if (err_number == 933) then
            msg = "Error: Solver type is not selected."
        else if (err_number == 934) then
            msg = "Error: Freezing calculation is not selected."
        else if (err_number == 941) then
            msg = "Error: The solution to the simultaneous linear equations could not be found."
        else if (err_number == 942) then
            msg = "Error: LU decomposition could not be successed."
        else if (err_number == 943) then
            msg = "Error: The inverse matrix could not be found."
        else if (err_number == 944) then
            msg = "Error: The target result is too high."
        else if (err_number == 945) then
            msg = "Error: The target result is too low."
        else if (err_number == 946) then
            msg = "Error: The solution has been diverged."
        else if (err_number == 951) then
            write (msg, '(a)') "Error: The number of vector elements must be positive."
        else if (err_number == 952) then
            write (msg, '(a)') "Error: The number of matrix elements must be positive."
        else if (err_number == 953) then
            write (msg, '(a)') "Error: Vector has already allocated."
        else if (err_number == 954) then
            write (msg, '(a)') "Error: Matrix has already allocated."
        else if (err_number == 955) then
            write (msg, '(a)') "Error: Pointer has already allocated."
        else
            msg = "Error: Unknown error"
        end if
#ifdef _MPI
        if (myrank == 0) then
            call MPI_Finalize(ierr)
#endif
            write (*, '(a)') msg
            stop
#ifdef _MPI
        end if
#endif
    end subroutine error_message
Call graph
error_message calls mpi_finalize
check_allocate_rank2_int32 calls error_message
check_allocate_rank1_logical calls error_message
inout_setprojectpath_setprojectpath calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
inout_output_all_dat calls error_message
solver_lu calls error_message
check_allocate_pointer_int32 calls error_message
check_allocate_rank1_real64 calls error_message
check_allocate_rank2_real64 calls error_message
check_allocate_rank1_int32_specify calls error_message
inout_output_all_vtk calls error_message
set_point_31 calls error_message
calc_area_31 calls error_message, set_point
calc_shape_31 calls error_message, set_point
check_allocate_pointer_real64 calls error_message
allocate_matrix calls check_allocate_rank2_int32, check_allocate_rank2_real64
allocate_vector calls check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32, check_allocate_rank1_real64, check_allocate_rank1_int32_specify
inout_setprojectpath_getprojectpath calls inout_setprojectpath_setprojectpath
calc_area calls calc_area_31
calc_shape calls calc_shape_31
inout_output_all calls inout_output_all_dat, inout_output_all_vtk
allocate_pointer calls check_allocate_pointer_int32, check_allocate_pointer_real64
set_point calls set_point_31
calc_gm_time_trm_f calls allocate_matrix
convert_crs calls allocate_vector
allocate_solver calls allocate_matrix, allocate_vector, allocate_df, allocate_dp2d
set_obs_coo_31 calls allocate_matrix, allocate_vector, set_point
allocate_df calls allocate_vector
set_boundary_condition_infomations calls allocate_vector
allocate_int2d calls allocate_vector
solve_initialize_bicgstab calls allocate_matrix
output_constructor calls allocate_vector, inout_setprojectpath_getprojectpath
allocate_dp2d calls allocate_vector
allocate_bcinfo calls allocate_vector, allocate_int2d
initialize_solver calls allocate_pointer
set_obs_coo calls set_obs_coo_31
ils calls solve_initialize_bicgstab
output calls output_constructor
heat_constructor calls set_boundary_condition_infomations
heat calls heat_constructor