Find_CRS_Indexes – FTDSS
Find_CRS_Indexes Subroutine
21 statements
Source File
public subroutine Find_CRS_Indexes(lump, A, serch_index1, serch_index2, serch_index3, indexes)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: lump
type(CRS), intent(in) :: A
integer(kind=int32), intent(in) :: serch_index1
integer(kind=int32), intent(in) :: serch_index2
integer(kind=int32), intent(in) :: serch_index3
integer(kind=int32), intent(inout) :: indexes(:)
Calls
Called by
Contents
Source Code
Find_CRS_Indexes
Source Code
    subroutine Find_CRS_Indexes(lump, A, serch_index1, serch_index2, serch_index3, indexes)
        implicit none
        type(CRS),      intent(in)    :: A
        integer(int32), intent(in)    :: lump, serch_index1, serch_index2, serch_index3
        integer(int32), intent(inout) :: indexes(:)
        if (lump == udmp) then
            call Find_CRS_Index(A, serch_index1, serch_index1, indexes(1))
            call Find_CRS_Index(A, serch_index1, serch_index2, indexes(2))
            call Find_CRS_Index(A, serch_index1, serch_index3, indexes(3))
            call Find_CRS_Index(A, serch_index2, serch_index1, indexes(4))
            call Find_CRS_Index(A, serch_index2, serch_index2, indexes(5))
            call Find_CRS_Index(A, serch_index2, serch_index3, indexes(6))
            call Find_CRS_Index(A, serch_index3, serch_index1, indexes(7))
            call Find_CRS_Index(A, serch_index3, serch_index2, indexes(8))
            call Find_CRS_Index(A, serch_index3, serch_index3, indexes(9))
        else if (lump == dmp) then
            call Find_CRS_Index(A, serch_index1, serch_index1, indexes(1))
            call Find_CRS_Index(A, serch_index2, serch_index2, indexes(2))
            call Find_CRS_Index(A, serch_index3, serch_index3, indexes(3))
        end if
    end subroutine Find_CRS_Indexes
Call graph
find_crs_indexes calls find_crs_index
calc_gm_time_trm calls find_crs_indexes
calc_gm_diffusion calls find_crs_indexes
calc_gm_time_divide calls find_crs_indexes
calc_gm_diffusion_trm calls find_crs_indexes
calc_gm_time_richards calls find_crs_indexes
calc_gm_diffusion_richards calls find_crs_indexes
calc_gm_diffusion_advection_trm calls find_crs_indexes
calc_gm_diffusion_advection calls find_crs_indexes
assemble_gm_heat calls calc_gm_time_trm, calc_gm_diffusion, calc_gm_time_divide, calc_gm_diffusion_trm, calc_gm_diffusion_advection_trm, calc_gm_diffusion_advection
assemble_gm_heat_ic calls calc_gm_time_trm, calc_gm_diffusion, calc_gm_time_divide, calc_gm_diffusion_trm
assemble_gm_water calls calc_gm_time_richards
fix_initialcondition_gradient_heat calls assemble_gm_heat_ic
fix_initialcondition calls fix_initialcondition_gradient_heat