Find_CRS_Index – FTDSS
Find_CRS_Index Subroutine
15 statements
Source File
public subroutine Find_CRS_Index(A, serch_column, serch_index, index)
Arguments
Type Intent Optional Attributes Name
type(CRS), intent(in) :: A
integer(kind=int32), intent(in) :: serch_column
integer(kind=int32), intent(in) :: serch_index
integer(kind=int32), intent(inout) :: index
Called by
Contents
Source Code
Find_CRS_Index
Source Code
    subroutine Find_CRS_Index(A, serch_column, serch_index, index)
        implicit none
        type(CRS),      intent(in)    :: A
        integer(int32), intent(in)    :: serch_column, serch_index
        integer(int32), intent(inout) :: index
        integer(int32)                :: i, start_index, end_index
        index = 0
        ! serch_columnのindex範囲を取得
        start_index = A%Ptr(serch_column - 1)
        end_index   = A%Ptr(serch_column) - 1
        ! 範囲内でserch_indexになる値のインデックスを見つける
        do i = start_index, end_index
            if (A%Ind(i) == serch_index - 1) then
                index = i
            end if
        end do
    end subroutine Find_CRS_Index
Call graph
find_crs_indexes calls find_crs_index
fix_dirichletboundarycondition_water calls find_crs_index
fix_dirichletboundarycondition_temperature calls find_crs_index
calc_gm_diffusion_richards calls find_crs_indexes
calc_gm_diffusion_advection_trm calls find_crs_indexes
calc_gm_diffusion_advection calls find_crs_indexes
calc_gm_time_divide calls find_crs_indexes
calc_gm_time_trm calls find_crs_indexes
calc_gm_diffusion_trm calls find_crs_indexes
calc_gm_time_richards calls find_crs_indexes
calc_gm_diffusion calls find_crs_indexes
fix_boundaryconditions calls fix_dirichletboundarycondition_temperature
assemble_gm_heat_ic calls calc_gm_time_divide, calc_gm_time_trm, calc_gm_diffusion_trm, calc_gm_diffusion
fix_initialcondition_gradient_water calls fix_boundaryconditions
assemble_gm_water calls calc_gm_time_richards
assemble_gm_heat calls calc_gm_diffusion_advection_trm, calc_gm_diffusion_advection, calc_gm_time_divide, calc_gm_time_trm, calc_gm_diffusion_trm, calc_gm_diffusion
fix_initialcondition_gradient_heat calls fix_boundaryconditions, assemble_gm_heat_ic
fix_initialcondition calls fix_initialcondition_gradient_water, fix_initialcondition_gradient_heat