Fix_InitialCondition – FTDSS
Fix_InitialCondition Subroutine
25 statements
Source File
public subroutine Fix_InitialCondition(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Contents
Source Code
Fix_InitialCondition
Source Code
    subroutine Fix_InitialCondition(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        if (Solver%isHeat) then
            if (Solver%IC%Heat%type == 1) then
                call Fix_InitialCondtion_Constant_Heat(Solver)
            else if (Solver%IC%Heat%type == 2) then
                call Fix_InitialCondition_Gradient_Heat(Solver)
                Solver%IC%Heat%isSet = .false.
            end if
            if (Solver%Flags%isStdOut) write(*,'(a)') "Set initial value of Temperature."
        end if
        if (Solver%isWater) then
            if (Solver%IC%Water%type == 1) then
                call Fix_InitialCondtion_Constant_Water(Solver)
            else if (Solver%IC%Water%type == 2) then
                call Fix_InitialCondition_Gradient_Water(Solver)
                Solver%IC%Water%isSet = .false.
            end if
            if (Solver%Flags%isStdOut) write(*,'(a)') "Set initial value of Pressure."
        end if
        if (Solver%isStress) then
            ! To be implemented
            ! if (Solver%IC%Stress%type == 1) then
            !     call Fix_InitialCondtion_Constant(Solver)
            ! else if (Solver%IC%Stress%type == 2) then
            !     call Fix_InitialCondition_Gradient(Solver)
            ! end if
            ! if (Solver%Flags%isStdOut) write(*,'(a)') "Set initial value of Stress."
        end if
        call Fix_InitialCondition_FreezingRate(Solver)
    end subroutine Fix_InitialCondition
Call graph
fix_initialcondition calls fix_initialcondtion_constant_heat, fix_initialcondtion_constant_water, fix_initialcondition_gradient_water, fix_initialcondition_gradient_heat, fix_initialcondition_freezingrate
fix_initialcondition_gradient_water calls update_parameters_water, fix_boundaryconditions, assemble_gm_water_ic
fix_initialcondition_gradient_heat calls assemble_gm_heat_ic, fix_boundaryconditions, update_parameters_heat
update_parameters_water calls update_variables_log
assemble_gm_heat_ic calls matrix_vector_product_crs, calc_gm_time_divide, calc_gm_diffusion, calc_gm_diffusion_trm, calc_gm_time_trm
fix_boundaryconditions calls fix_dirichletboundarycondition_temperature, fix_dirichletboundarycondition_water_f
assemble_gm_water_ic calls calc_gm_diffusion_richards_f
update_parameters_heat calls update_cpa_gcc, update_cadiv, update_variables_geometric, update_heat_flux, update_cpa_power, update_gradient, update_variables_arithmetic, update_phase, update_theta, update_flux
calc_gm_time_divide calls set_c, find_crs_indexes
calc_gm_diffusion calls find_crs_indexes
fix_dirichletboundarycondition_temperature calls find_crs_index
calc_gm_diffusion_trm calls find_crs_indexes
calc_gm_time_trm calls find_crs_indexes
find_crs_indexes calls find_crs_index