Fix_BoundaryConditions – FTDSS
Fix_BoundaryConditions Subroutine
29 statements
Source File
public subroutine Fix_BoundaryConditions(Solver, inTarget)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
integer(kind=int32), intent(in) :: inTarget
Calls
Called by
Contents
Source Code
Fix_BoundaryConditions
Source Code
    subroutine Fix_BoundaryConditions(Solver, inTarget)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        integer(int32), intent(in) :: inTarget
        integer(int32) :: iBC, i
        integer(int32) :: iBCType
        integer(int32) :: p1, p2
        do iBC = 1, Solver%BC%numNode
            if (inTarget == Tmp) then
                iBCType = Solver%BC%Heat%type(Solver%BC%Heat%TypeKey(iBC))
                if (10 <= iBCType .and. iBCType <= 19) then
                    call Fix_DirichletBoundaryCondition_Temperature(Solver, iBC)
                    ! call Fix_DirichletBoundaryCondition_Temperature_F(Solver, iBC)
                end if
            else if (inTarget == Prs) then
                iBCType = Solver%BC%Water%type(Solver%BC%Water%TypeKey(iBC))
                if (10 <= iBCType .and. iBCType <= 19) then
                    ! call Fix_DirichletBoundaryCondition_Water(Solver, iBC)
                    call Fix_DirichletBoundaryCondition_Water_F(Solver, iBC)
                end if
            end if
            ! stop
            ! Solver%Water%Variables%wFlux%y(Solver%BC%Water%TypeKey(iBC)) = 0.0d0
            ! if (Solver%BC%Water%TypeKey(iBC) == 4) Solver%Water%Variables%wFlux%x(Solver%BC%Water%TypeKey(iBC)) = 0.0d0
        end do
        if (inTarget == Tmp .and. Solver%BC%numEdges > 0) then
            do i = 1, Solver%BC%numEdges
                p1 = Solver%BC%Heat%Edges%x(i)
                p2 = Solver%BC%Heat%Edges%y(i)
                Solver%Heat%Rhs(p1) = Solver%Heat%Rhs(p1) - (2.0d0 * Solver%Heat%Variables%TFlux%x(p1) + Solver%Heat%Variables%TFlux%x(p2)) * Solver%BC%Heat%EdgesDistance(i) / 6.0d0
                Solver%Heat%Rhs(p2) = Solver%Heat%Rhs(p2) - (Solver%Heat%Variables%TFlux%x(p1) + 2.0d0 * Solver%Heat%Variables%TFlux%x(p2)) * Solver%BC%Heat%EdgesDistance(i) / 6.0d0
                ! print*,Solver%Heat%Rhs(p1),Solver%Heat%Rhs(p2)
                ! print*,Solver%Heat%Variables%TFlux%x(p1),Solver%Heat%Variables%TFlux%x(p2)
                ! print*,(Solver%N%vCood%x(Solver%BC%Heat%Edges%y(i)) - Solver%N%vCood%x(Solver%BC%Heat%Edges%x(i))),(Solver%N%vCood%y(Solver%BC%Heat%Edges%y(i)) - Solver%N%vCood%y(Solver%BC%Heat%Edges%x(i)))
            end do
            ! print*, Solver%BC%Heat%EdgesDistance(:)
            ! print *, "Water"
            ! stop
        end if
    end subroutine Fix_BoundaryConditions
Call graph
fix_boundaryconditions calls fix_dirichletboundarycondition_temperature, fix_dirichletboundarycondition_water_f
fix_dirichletboundarycondition_temperature calls find_crs_index
fix_initialcondition_gradient_heat calls fix_boundaryconditions
fix_initialcondition_gradient_water calls fix_boundaryconditions
fix_initialcondition calls fix_initialcondition_gradient_heat, fix_initialcondition_gradient_water