Fix_DirichletBoundaryCondition_Water_F – FTDSS
Fix_DirichletBoundaryCondition_Water_F Subroutine
10 statements
Source File
private subroutine Fix_DirichletBoundaryCondition_Water_F(Solver, iBC)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
integer(kind=int32), intent(in) :: iBC
Called by
Contents
Source Code
Fix_DirichletBoundaryCondition_Water_F
Source Code
    subroutine Fix_DirichletBoundaryCondition_Water_F(Solver, iBC)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        integer(int32), intent(in) :: iBC
        integer(int32) :: iCol, ind, ps, pe
        iCol = Solver%BC%Water%Node(iBC)
        Solver%Water%RA(iCol, :) = 0.0d0
        Solver%Water%RA(iCol, iCol) = 1.0d0
        Solver%Water%Rhs(iCol) = Solver%BC%Water%value(Solver%BC%Water%TypeKey(iBC))
    end subroutine Fix_DirichletBoundaryCondition_Water_F
Call graph
fix_boundaryconditions calls fix_dirichletboundarycondition_water_f
fix_initialcondition_gradient_heat calls fix_boundaryconditions
fix_initialcondition_gradient_water calls fix_boundaryconditions
fix_initialcondition calls fix_initialcondition_gradient_heat, fix_initialcondition_gradient_water