Fix_InitialCondition_Gradient_Heat – FTDSS
Fix_InitialCondition_Gradient_Heat Subroutine
13 statements
Source File
private subroutine Fix_InitialCondition_Gradient_Heat(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Called by
Contents
Source Code
Fix_InitialCondition_Gradient_Heat
Source Code
    subroutine Fix_InitialCondition_Gradient_Heat(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        type(ILS),allocatable :: ILEQ
        integer(int32) :: ierr
        ILEQ = ILS(Solver, Solver%Heat%LHS_A)
        call Update_Parameters_Heat(Solver)
        call Assemble_GM_Heat_IC(Solver)
        call Fix_BoundaryConditions(Solver, Temperature)
        call ILEQ%BiCGStab(Solver, Solver%Heat%LHS_A, Solver%Heat%Rhs, Solver%T%pre, ierr)
        call ILEQ%Chkerr(ierr, 0.0d0)
        deallocate(ILEQ)
    end subroutine Fix_InitialCondition_Gradient_Heat
Call graph
fix_initialcondition_gradient_heat calls update_parameters_heat, assemble_gm_heat_ic, fix_boundaryconditions
update_parameters_heat calls update_theta, update_cadiv, update_variables_arithmetic, update_flux, update_cpa_power, update_variables_geometric, update_cpa_gcc, update_phase, update_gradient, update_heat_flux
assemble_gm_heat_ic calls calc_gm_time_trm, calc_gm_diffusion, matrix_vector_product_crs, calc_gm_diffusion_trm, calc_gm_time_divide
fix_boundaryconditions calls fix_dirichletboundarycondition_water_f, fix_dirichletboundarycondition_temperature
calc_gm_time_trm calls find_crs_indexes
calc_gm_diffusion calls find_crs_indexes
calc_gm_diffusion_trm calls find_crs_indexes
calc_gm_time_divide calls find_crs_indexes, set_c
fix_dirichletboundarycondition_temperature calls find_crs_index
find_crs_indexes calls find_crs_index
fix_initialcondition calls fix_initialcondition_gradient_heat