Fix_InitialCondition_Gradient_Water – FTDSS
Fix_InitialCondition_Gradient_Water Subroutine
13 statements
Source File
private subroutine Fix_InitialCondition_Gradient_Water(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Called by
Contents
Source Code
Fix_InitialCondition_Gradient_Water
Source Code
    subroutine Fix_InitialCondition_Gradient_Water(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        type(DLS) ::DLEQ
        Solver%Si%old(:) = Solver%Si%pre(:)
        Solver%Si%pre(:) = 0.0d0
        call Update_Parameters_Water(Solver)
        Solver%Si%pre(:) = Solver%Si%old(:)
        call Assemble_GM_Water_IC(Solver)
        call Fix_BoundaryConditions(Solver, Pressure)
        DLEQ = DLS(Solver)
        call DLEQ%LU(Solver%Water%RA, Solver%Water%Rhs, Solver%P%pre)
    end subroutine Fix_InitialCondition_Gradient_Water
Call graph
fix_initialcondition_gradient_water calls update_parameters_water, fix_boundaryconditions, assemble_gm_water_ic
update_parameters_water calls update_variables_log
fix_boundaryconditions calls fix_dirichletboundarycondition_temperature, fix_dirichletboundarycondition_water_f
assemble_gm_water_ic calls calc_gm_diffusion_richards_f
fix_dirichletboundarycondition_temperature calls find_crs_index
fix_initialcondition calls fix_initialcondition_gradient_water