Heat_Constructor – FTDSS
Heat_Constructor Function
11 statements
Source File
private function Heat_Constructor(Structure_Input)
Arguments
Type Intent Optional Attributes Name
type(Input), intent(in) :: Structure_Input
Return Value type(Heat)
Calls
Called by
Contents
Source Code
Heat_Constructor
Source Code
    type(Heat) function Heat_Constructor(Structure_Input)
        type(Input), intent(in) :: Structure_Input
        call Set_Geometory_Infomation(Heat_Constructor, Structure_Input)
        call Set_Boundary_Condition_Infomations(Heat_Constructor, Structure_Input)
        block
            real(real64) :: array_HCF(9)
            array_HCF = [1, 2, 3, 4, 5, 6, 7, 8, 9]
            print *, array_HCF
            Heat_Constructor%HCFs = HCF(array_HCF, 5, 2)
        end block
    end function Heat_Constructor
Call graph
heat_constructor calls set_geometory_infomation, hcf, array_hcf, set_boundary_condition_infomations
hcf calls hcf_constructor
set_boundary_condition_infomations calls count_if, condition_in_boundarycondition, condition_heat, allocate_vector
count_if calls count_if_int32, count_if_int32_array
allocate_vector calls check_allocate_rank1_real64, check_allocate_rank1_int32_specify, check_allocate_rank1_int32, check_allocate_rank1_logical, check_allocate_rank1_real64_specify
check_allocate_rank1_real64 calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
error_message calls mpi_finalize
heat calls heat_constructor