Initialize_Solver – FTDSS
Initialize_Solver Subroutine
35 statements
Source File
public subroutine Initialize_Solver(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Contents
Source Code
Initialize_Solver
Source Code
    subroutine Initialize_Solver(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        integer(int32)                  :: i
        call Allocate_Pointer(Solver%Time%tst)
        call Allocate_Pointer(Solver%Time%dt)
        call Allocate_Pointer(Solver%Time%odt)
        ! Time settings converting to seconds
        Solver%Time%ts     = 0.0d0
        Solver%Time%tst    = 0.0d0
        Solver%Time%te     = Solver%Time%cTime * Convert_TimeUnit(Solver%Time, 1)
        Solver%Time%dt     = Solver%Time%cdt   * Convert_TimeUnit(Solver%Time, 2)
        Solver%Time%odt    = Solver%Time%dt
        Solver%Time%max_dt = 1.0d-8
        Solver%Time%min_dt = 300.0d0
        Solver%Time%tconv  = 1.0d0 / Convert_TimeUnit(Solver%Time, 1)
        call Allocate_Pointer(Solver%Iter%iter)
        call Allocate_Pointer(Solver%Iter%titer)
        call Allocate_Pointer(Solver%Iter%iNL)
        ! Iteration settings
        Solver%Iter%iter           = 1
        Solver%Iter%itermax        = nint(Solver%Time%te / Solver%Time%cinterval)
        Solver%Iter%titer          = 1
        Solver%Iter%iNL            = 1
        Solver%Iter%iNLmax         = 50
        Solver%Iter%iNI            = 1
        Solver%Iter%digits_itermax = int(log10(dble(Solver%Iter%itermax))) + 1
        ! Output format settings
        write(Solver%fmt_Stdout,  '(a,i0,a,i0,a)'), &
                                  '(a,i', Solver%Iter%digits_itermax, ',a,i', Solver%Iter%digits_itermax,',a,f9.4,a,f11.4,a)'
        write(Solver%fmt_Fileout, '(a,i0,a,i0,a)'), &
                                  '(2a,i', Solver%Iter%digits_itermax, '.', Solver%Iter%digits_itermax, ',a)'
        Solver%Heat%Latent%Cp_unf = Solver%Heat%Constants%HeatCapacity%soil  * (1.0d0 - Solver%Heat%Constants%Porosity) &
                                  + Solver%Heat%Constants%HeatCapacity%water * Solver%Heat%Constants%Porosity
        ! Find the maximum value of Ca
        call Find_Ca_max(Solver%Heat)
        if (Solver%BC%numEdges > 0) then
            do i = 1, Solver%BC%numEdges
                ! print*,(Solver%N%vCood%x(Solver%BC%Heat%Edges%y(i)) - Solver%N%vCood%x(Solver%BC%Heat%Edges%x(i))),(Solver%N%vCood%y(Solver%BC%Heat%Edges%y(i)) - Solver%N%vCood%y(Solver%BC%Heat%Edges%x(i)))
                Solver%BC%Heat%EdgesDistance(i) = sqrt((Solver%N%vCood%x(Solver%BC%Heat%Edges%y(i)) - Solver%N%vCood%x(Solver%BC%Heat%Edges%x(i)))**2.0d0 + (Solver%N%vCood%y(Solver%BC%Heat%Edges%y(i)) - Solver%N%vCood%y(Solver%BC%Heat%Edges%x(i)))**2.0d0)
            end do
        end if
    end subroutine Initialize_Solver
Call graph
initialize_solver calls allocate_pointer, convert_timeunit, find_ca_max
allocate_pointer calls check_allocate_pointer_real64, check_allocate_pointer_int32
find_ca_max calls calc_ca_gcc
check_allocate_pointer_real64 calls error_message
check_allocate_pointer_int32 calls error_message
error_message calls mpi_finalize