Inout_Output_All_Dat – FTDSS
Inout_Output_All_Dat Subroutine
29 statements
Source File
private subroutine Inout_Output_All_Dat(self, Solver, num)
Arguments
Type Intent Optional Attributes Name
class(Output) :: self
type(SolverInfo), intent(inout) :: Solver
integer(kind=int32), intent(in) :: num
Calls
Called by
Contents
Source Code
Inout_Output_All_Dat
Source Code
    subroutine Inout_Output_All_Dat(self, Solver, num)
        implicit none
        class(Output) :: self
        type(SolverInfo), intent(inout) :: Solver
        integer(int32), intent(in) :: num
        character(256) :: oName, fmt
        integer(int32) :: ios, unit_num, iN
        write (oName, Solver%fmt_Fileout) trim(self%dir_Path), "Output/DATFILE/Output_", num, ".dat"
        open (newunit=unit_num, file=oName, status='replace', action='write', iostat=ios)
        if (ios /= 0) call error_message(931)
        select case (Solver%nAnalysis)
        case (1)
            ! do iN = 1, Solver%N%node
            !     write(unit_num, '(es15.7,a,es15.7)') Solver%T%pre(iN), ', ', Solver%T%Si(iN)
            ! end do
        case (2)
        case (3)
        case (4)
            fmt = '(2es13.5,2es13.5)'
            do iN = 1, Solver%N%node
                write (unit_num, fmt) Solver%N%vCood%x(iN), Solver%N%vCood%y(iN), Solver%T%pre(iN), Solver%Si%pre(iN)
            end do
        case (5)
        case (6)
            fmt = '(2es13.5,5es13.5)'
            do iN = 1, Solver%N%node
                write (unit_num, fmt) Solver%N%vCood%x(iN), Solver%N%vCood%y(iN), Solver%T%pre(iN), Solver%P%pre(iN), Solver%Si%pre(iN), Solver%Water%Variables%wFlux%x(iN), +Solver%Water%Variables%wFlux%y(iN)
            end do
        case (7)
        end select
        close (unit_num)
    end subroutine Inout_Output_All_Dat
Call graph
inout_output_all_dat calls error_message
error_message calls mpi_finalize
inout_output_all calls inout_output_all_dat