Inout_SetProjectPath_GetProjectPath – FTDSS
Inout_SetProjectPath_GetProjectPath Function
5 statements
Source File
public function Inout_SetProjectPath_GetProjectPath()
Arguments
None
Return Value character(len=256)
Calls
Called by
Contents
Source Code
Inout_SetProjectPath_GetProjectPath
Source Code
    character(256) function Inout_SetProjectPath_GetProjectPath()
        implicit none
        if (.not. isSetProjectPath) call Inout_SetProjectPath_SetProjectPath
        Inout_SetProjectPath_GetProjectPath = ProjectPath
    end function Inout_SetProjectPath_GetProjectPath
Call graph
inout_setprojectpath_getprojectpath calls inout_setprojectpath_setprojectpath
inout_setprojectpath_setprojectpath calls error_message
error_message calls mpi_finalize
output_constructor calls inout_setprojectpath_getprojectpath
output calls output_constructor