Matrix_Vector_Product_CRS – FTDSS
Matrix_Vector_Product_CRS Subroutine
20 statements
Source File
public subroutine Matrix_Vector_Product_CRS(A, x, y)
Arguments
Type Intent Optional Attributes Name
type(CRS), intent(in) :: A
real(kind=real64), intent(in) :: x(:)
real(kind=real64), intent(inout) :: y(:)
Called by
Contents
Source Code
Matrix_Vector_Product_CRS
Source Code
    subroutine Matrix_Vector_Product_CRS(A, x, y)
        implicit none
        type(CRS), intent(in) :: A
        real(real64), intent(in) :: x(:)
        real(real64), intent(inout) :: y(:)
        real(real64) :: vtemp
        integer(int32) :: i, j, is, ie
        integer(int32) :: matrix_size
        matrix_size = size(A%ptr) - 1
        y(:) = 0.0d0
        !$omp parallel do private(vtemp, i, j, is, ie)
        do i = 1, matrix_size
            vtemp = 0.0d0
            is = A%ptr(i - 1)
            ie = A%ptr(i) - 1
            do j = is, ie
                vtemp = vtemp + A%val(j) * x(A%ind(j) + 1)
            end do
            y(i) = vtemp
        end do
        !$omp end parallel do
    end subroutine Matrix_Vector_Product_CRS
Call graph
assemble_gm_heat calls matrix_vector_product_crs
solver_bicgstab calls matrix_vector_product_crs
assemble_gm_heat_ic calls matrix_vector_product_crs
assemble_gm_water calls matrix_vector_product_crs
fix_initialcondition_gradient_heat calls assemble_gm_heat_ic
fix_initialcondition calls fix_initialcondition_gradient_heat