Output_Constructor – FTDSS
Output_Constructor Function
31 statements
Source File
private function Output_Constructor(Inputs)
Arguments
Type Intent Optional Attributes Name
type(Input), intent(in) :: Inputs
Return Value type(Output)
Calls
Called by
Contents
Source Code
Output_Constructor
Source Code
    type(Output) function Output_Constructor(Inputs)
        implicit none
        type(Input), intent(in) :: Inputs
        integer(int32) :: Flag_Size
        integer(int32), allocatable :: Output_Observation_Flag(:)
        ! character(256) :: dir_Path
        integer :: i
        integer(int32) :: Output_File_Type
        ! Path settings
        Output_Constructor%dir_Path = GetProjectPath()
        Output_File_Type = Inputs%Input_Get_Output_File()
        if (Output_File_Type == 1) then
            Output_Constructor%is_Output_Dat = .true.
            Output_Constructor%is_Output_VTK = .false.
        else if (Output_File_Type == 2) then
            Output_Constructor%is_Output_Dat = .false.
            Output_Constructor%is_Output_VTK = .true.
        end if
        Output_Constructor%T_FileName = trim(Output_Constructor%dir_Path)//"Output/obsf_T.dat"
        Output_Constructor%Fr_FileName = trim(Output_Constructor%dir_Path)//"Output/obsf_Fr.dat"
        Output_Constructor%TC_FileName = trim(Output_Constructor%dir_Path)//"Output/obsf_TC.dat"
        Output_Constructor%C_FileName = trim(Output_Constructor%dir_Path)//"Output/obsf_C.dat"
        Output_Constructor%P_FileName = trim(Output_Constructor%dir_Path)//"Output/obsf_P.dat"
        Output_Constructor%Flux_FileName = trim(Output_Constructor%dir_Path)//"Output/obsf_Flux.dat"
        Output_Constructor%K_FileName = trim(Output_Constructor%dir_Path)//"Output/obsf_K.dat"
        Output_Observation_Flag = Inputs%Input_Get_Observation_Flag()
        Flag_Size = size(Output_Observation_Flag)
        call Allocate_Vector(Output_Constructor%is_Output, Flag_Size)
        do i = 1, Flag_Size
            call Set_Output_Flag(Output_Observation_Flag(i), Output_Constructor%is_Output(i))
        end do
        if (allocated(Output_Observation_Flag)) deallocate (Output_Observation_Flag)
    end function Output_Constructor
Call graph
output_constructor calls inout_setprojectpath_getprojectpath, allocate_vector, set_output_flag
inout_setprojectpath_getprojectpath calls inout_setprojectpath_setprojectpath
allocate_vector calls check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32, check_allocate_rank1_int32_specify, check_allocate_rank1_real64
inout_setprojectpath_setprojectpath calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
error_message calls mpi_finalize
output calls output_constructor