Set_Obs_COO_31 – FTDSS
Set_Obs_COO_31 Subroutine
24 statements
Source File
private subroutine Set_Obs_COO_31(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Called by
Contents
Source Code
Set_Obs_COO_31
Source Code
    subroutine Set_Obs_COO_31(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        type(Vector2d)                  :: p1, p2, p3
        integer(int32)                  :: iE, iObs, iS
        real(real64)                    :: x,y,s
        call Allocate_Vector(Solver%Obs%nAreaObs, Solver%Obs%nObs)
        call Allocate_Matrix(Solver%Obs%vAreaObs, Solver%N%ShCoe, Solver%Obs%nObs)
        do iObs = 1, Solver%Obs%nObs
            x = Solver%Obs%obsCOO%x(iObs)
            y = Solver%Obs%obsCOO%y(iObs)
            do iE = 1, Solver%N%Element
                call Set_Point(Solver%N, iE, p1, p2, p3)
                if (is_in_triangle(x, y, p1, p2, p3)) then
                    s = Solver%N%eArea(iE)
                    do iS = 1, Solver%N%ShCoe
                        Solver%Obs%vAreaObs(iS, iObs) = (Solver%N%Basis%a(iS, iE) + Solver%N%Basis%b(iS, iE) * x &
                                                    & +  Solver%N%Basis%c(iS, iE) * y) / (2.0d0 * s)
                    end do
                    Solver%Obs%nAreaObs(iObs)         = iE
                    exit
                end if
            end do
        end do
    end subroutine Set_Obs_COO_31
Call graph
set_obs_coo_31 calls allocate_vector, is_in_triangle, set_point, allocate_matrix
allocate_vector calls check_allocate_rank1_int32_specify, check_allocate_rank1_real64, check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32
set_point calls set_point_31
allocate_matrix calls check_allocate_rank2_real64, check_allocate_rank2_int32
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
set_point_31 calls error_message
check_allocate_rank2_real64 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank2_int32 calls error_message
error_message calls mpi_finalize
set_obs_coo calls set_obs_coo_31