Set_Boundary_Condition_Infomations – FTDSS
Set_Boundary_Condition_Infomations Subroutine
42 statements
Source File
private subroutine Set_Boundary_Condition_Infomations(self, Structure_Input)
Uses
Calculate_Count
Arguments
Type Intent Optional Attributes Name
type(Heat), intent(inout) :: self
type(Input), intent(in) :: Structure_Input
Calls
Called by
Contents
Source Code
Set_Boundary_Condition_Infomations
Source Code
    subroutine Set_Boundary_Condition_Infomations(self, Structure_Input)
        use :: Calculate_Count, only:Count_if
        implicit none
        type(Heat), intent(inout) :: self
        type(Input), intent(in) :: Structure_Input
        integer(int32) :: Count_Heat
        integer(int32) :: iBC, Counter
        integer(int32), allocatable :: Work_Node(:), Work_Edge(:, :), Work_Type(:), Work_Value_Info(:, :)
        real(real64), allocatable :: Work_Value(:)
        Work_Node = Structure_Input%Input_Get_BC_Node()
        Work_Type = Structure_Input%Input_Get_BC_Node_Type()
        Work_Value_Info = Structure_Input%Input_Get_BC_Node_Value_Info()
        Work_Value = Structure_Input%Input_Get_BC_Node_Value(Calc_Heat)
        self%BC%Dirichlet%Num_Type = Count_if(Work_Value_Info(:, 2), Condition_Heat)
        call Allocate_Vector(self%BC%Dirichlet%Value_Info, self%BC%Dirichlet%Num_Type)
        call Allocate_Vector(self%BC%Dirichlet%value, self%BC%Dirichlet%Num_Type)
        Counter = 0
        do iBC = 1, size(Work_Value_Info(:, 2))
            if (Condition_Heat(Work_Value_Info(iBC, 2))) then
                Counter = Counter + 1
                self%BC%Dirichlet%Value_Info(Counter) = Work_Value_Info(iBC, 1)
                self%BC%Dirichlet%value(Counter) = Work_Value(iBC)
            end if
        end do
        self%BC%Dirichlet%Num_Node = Count_if(Work_Type(:), Condition_In_BoundaryCondition, self%BC%Dirichlet%Value_Info(:))
        call Allocate_Vector(self%BC%Dirichlet%Node, self%BC%Dirichlet%Num_Node)
        call Allocate_Vector(self%BC%Dirichlet%Node_Type, self%BC%Dirichlet%Num_Node)
        Counter = 0
        do iBC = 1, size(Work_Type)
            if (Condition_In_BoundaryCondition(Work_Type(iBC), self%BC%Dirichlet%Value_Info(:))) then
                Counter = Counter + 1
                self%BC%Dirichlet%Node(Counter) = Work_Node(iBC)
                self%BC%Dirichlet%Node_Type(Counter) = Work_Type(iBC)
            end if
        end do
        if (allocated(Work_Node)) deallocate (Work_Node)
        if (allocated(Work_Type)) deallocate (Work_Type)
        if (allocated(Work_Value_Info)) deallocate (Work_Value_Info)
        if (allocated(Work_Value)) deallocate (Work_Value)
        self%BC%Neumann%Edge = Structure_Input%Input_Get_BC_Edge()
        self%BC%Neumann%Edge_Type = Structure_Input%Input_Get_BC_Edge_Type()
    end subroutine Set_Boundary_Condition_Infomations
Call graph
set_boundary_condition_infomations calls count_if, allocate_vector, condition_heat, condition_in_boundarycondition
count_if calls count_if_int32, count_if_int32_array
allocate_vector calls check_allocate_rank1_real64, check_allocate_rank1_int32_specify, check_allocate_rank1_int32, check_allocate_rank1_logical, check_allocate_rank1_real64_specify
check_allocate_rank1_real64 calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
error_message calls mpi_finalize
heat_constructor calls set_boundary_condition_infomations
heat calls heat_constructor