Solver_BiCGStab – FTDSS
Solver_BiCGStab Subroutine
80 statements
Source File
private subroutine Solver_BiCGStab(self, Solver, BiCG_A, BiCG_b, BiCG_x, status)
Arguments
Type Intent Optional Attributes Name
class(ILS) :: self
type(SolverInfo), intent(inout) :: Solver
type(CRS), intent(in) :: BiCG_A
real(kind=real64), intent(in) :: BiCG_b(:)
real(kind=real64), intent(inout) :: BiCG_x(:)
integer(kind=int32), intent(inout) :: status
Calls
Contents
Source Code
Solver_BiCGStab
Source Code
    subroutine Solver_BiCGStab(self, Solver, BiCG_A, BiCG_b, BiCG_x, status)
        implicit none
        class(ILS)                      :: self
        type(SolverInfo), intent(inout) :: Solver
        type(CRS),        intent(in)    :: BiCG_A
        real(real64),     intent(in)    :: BiCG_b(:)
        real(real64),     intent(inout) :: BiCG_x(:)
        integer(int32),   intent(inout) :: status
        real(real64)                    :: rho, rho_old, alpha, beta, omega
        real(real64)                    :: tol, resid
        real(real64)                    :: ddot, dnrm2
        integer(int32)                  :: maxiter, iter, N, iN
        ! 1:Initialize
        N                 = Solver%N%node
        tol               = 1.0d-12
        maxiter           = N * 100
        maxiter           = 50000
        self%CRS_A%Val(:) = BiCG_A%Val(:)
        self%b(:)         = BiCG_b(:)
        rho               = 1.0d0
        rho_old           = 1.0d0
        alpha             = 1.0d0
        beta              = 1.0d0
        omega             = 1.0d0
        do iN = 1, N
            self%p(iN)    = 0.0d0
            self%s(iN)    = 0.0d0
            self%phat(iN) = 0.0d0
            self%shat(iN) = 0.0d0
        end do
        ! 2: Set an initial value x0
        self%x(:) = 0.0d0
        ! 3: r0 = b-Ax0
        call SpMV(self%CRS_A, self%x, self%r)
        do iN = 1, N
            self%r(iN) = self%b(iN) - self%r(iN)
        end do
        ! 4: Create preconditioned matrix
        call Create_Precond_Jacobi(N, self%CRS_A, self%M)
        ! 5: ^r0 = r0, (r*0, r0)!=0
        self%r0(:) = self%r(:)
        do iter = 1, maxiter, 1
            ! 7: (^r0, rk)
            rho = dot(N, self%r, self%r0)
            ! rho = ddot(N, self%r, 1, self%r0, 1)
            ! 8: rho check
            if (rho == 0.0d0) then
                status = 0
                BiCG_x(:) = self%x(:)
                return
            end if
            if (iter == 1) then
                ! 10: p0 = r0
                self%p(:) = self%r(:)
            else
                ! 12: beta = (rho / rho_old) * (alpha_k / omega_k)
                beta = (rho / rho_old) * (alpha / omega)
                ! 13: p_k = r_k + beta_k(p_(k-1) - omega_k * Av)
                do iN = 1, N
                    self%p(iN) = self%r(iN) + beta * (self%p(iN) - omega * self%v(iN))
                end do
            end if
            ! 15: phat = M^-1 * p
            call Apply_Precond_Jacobi(N, self%M, self%p, self%phat)
            ! 16: v = A * phat
            call SpMV(self%CRS_A, self%phat, self%v)
            ! 17: alpha_k = rho / (^r0, v)
            alpha = rho / dot(N, self%r0, self%v)
            ! alpha = rho / ddot(N, self%r0, 1, self%v, 1)
            ! 18: s = r_k - alpha_k * v
            do iN = 1, N
                self%s(iN) = self%r(iN) - alpha * self%v(iN)
            end do
            ! 19: shat = M^-1 * s
            call Apply_Precond_Jacobi(N, self%M, self%s, self%shat)
            ! 20: t = A * shat
            call SpMV(self%CRS_A, self%shat, self%t)
            ! 21: omega_k = (t,s)/(t,t)
            omega = dot(N, self%t, self%s) / dot(N, self%t, self%t)
            ! omega = ddot(N, self%t, 1, self%s, 1) / ddot(N, self%t, 1, self%t, 1)
            ! 22: omega breakdown check
            if (omega == 0.0d0) then
                status = -1
                return
            end if
            do iN = 1, N
                ! 23: x(i) = x(i-1) + alpha * M^-1 p(i-1) + omega * M^-1 s(i)
                self%x(iN) = self%x(iN) + alpha * self%phat(iN) + omega * self%shat(iN)
            end do
            do iN = 1, N
                ! 24: r(i) = s(i-1) - omega * AM^-1 s(i-1)
                self%r(iN) = self%s(iN) - omega * self%t(iN)
            end do
            ! 25: ||r_k+1||_2
            ! resid = dnrm2(N, self%r(:), 1)
            resid = norm(N, self%r(:))
            if (resid < tol) then
                status = 0
                BiCG_x(:) = self%x(:)
                return
            end if
            rho_old = rho
        end do
        status = -2
    end subroutine Solver_BiCGStab
Call graph
solver_bicgstab calls ddots, apply_precond_jacobi, matrix_vector_product_crs, norm_2, create_precond_jacobi