Solve_Initialize_BiCGStab – FTDSS
Solve_Initialize_BiCGStab Function
18 statements
Source File
private function Solve_Initialize_BiCGStab(Solver, MCRS)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(in) :: Solver
type(CRS), intent(in) :: MCRS
Return Value type(ILS)
Calls
Called by
Contents
Source Code
Solve_Initialize_BiCGStab
Source Code
    type(ILS) function Solve_Initialize_BiCGStab(Solver, MCRS)
        implicit none
        type(SolverInfo), intent(in) :: Solver
        type(CRS),        intent(in) :: MCRS
        call Allocate_Matrix(work,  Solver%N%node, 11)
        Solve_Initialize_BiCGStab%M    => work(:, 1)
        Solve_Initialize_BiCGStab%p    => work(:, 2)
        Solve_Initialize_BiCGStab%phat => work(:, 3)
        Solve_Initialize_BiCGStab%s    => work(:, 4)
        Solve_Initialize_BiCGStab%shat => work(:, 5)
        Solve_Initialize_BiCGStab%r    => work(:, 6)
        Solve_Initialize_BiCGStab%r0   => work(:, 7)
        Solve_Initialize_BiCGStab%t    => work(:, 8)
        Solve_Initialize_BiCGStab%v    => work(:, 9)
        Solve_Initialize_BiCGStab%x    => work(:, 10)
        Solve_Initialize_BiCGStab%b    => work(:, 11)
        call Duplicate_CRS(MCRS,  Solve_Initialize_BiCGStab%CRS_A)
    end function Solve_Initialize_BiCGStab
Call graph
solve_initialize_bicgstab calls allocate_matrix, duplicate_crs
allocate_matrix calls check_allocate_rank2_int32, check_allocate_rank2_real64
check_allocate_rank2_int32 calls error_message
check_allocate_rank2_real64 calls error_message
error_message calls mpi_finalize
ils calls solve_initialize_bicgstab