Solver_LU – FTDSS
Solver_LU Subroutine
11 statements
Source File
private subroutine Solver_LU(self, LU_A, LU_b, LU_x)
Arguments
Type Intent Optional Attributes Name
class(DLS) :: self
real(kind=real64), intent(inout) :: LU_A(:,:)
real(kind=real64), intent(inout) :: LU_b(:)
real(kind=real64), intent(inout) :: LU_x(:)
Calls
Contents
Source Code
Solver_LU
Source Code
    subroutine Solver_LU(self, LU_A, LU_b, LU_x)
        implicit none
        class(DLS) ::self
        real(real64),   intent(inout) :: LU_A(:,:), LU_b(:), LU_x(:)
        ! integer(int32), intent(in)    :: n
        integer(int32)                :: ipiv(self%N), info
        !* LU decomposition
        call Dgetrf(self%N, self%N, LU_A, self%N, ipiv, info)
        if (info /= 0) call error_message(942)
        !* solve linear equation
        call Dgetrs('N', self%N, 1, LU_A, self%N, ipiv, LU_b, self%N, info)
        if (info /= 0) call error_message(943)
        LU_x(:) = LU_b(:)
    end subroutine Solver_LU
Call graph
solver_lu calls dgetrf, error_message, dgetrs
error_message calls mpi_finalize