Update_Heat_Flux – FTDSS
Update_Heat_Flux Subroutine
11 statements
Source File
private subroutine Update_Heat_Flux(TFlux, C, TGrad, Cw, Qw, T)
Arguments
Type Intent Optional Attributes Name
type(DP2d), intent(inout) :: TFlux
real(kind=real64), intent(in) :: C(:)
type(DP2d), intent(in) :: TGrad
real(kind=real64), intent(in) :: Cw
type(DP2d), intent(in) :: Qw
real(kind=real64), intent(in) :: T(:)
Called by
Contents
Source Code
Update_Heat_Flux
Source Code
    subroutine Update_Heat_Flux(TFlux, C, TGrad, Cw, Qw, T)
        implicit none
        type(DP2d),   intent(inout) :: TFlux
        type(DP2d),   intent(in)    :: TGrad
        real(real64), intent(in)    :: C(:)
        real(real64), intent(in)    :: Cw
        type(DP2d),   intent(in)    :: Qw
        real(real64), intent(in)    :: T(:)
        TFlux%x(:) = - C(:) * TGrad%x(:)
        TFlux%y(:) = - C(:) * TGrad%y(:)
        ! print*, TFlux%x(:)
        ! stop
    end subroutine Update_Heat_Flux
Call graph
update_parameters_heat calls update_heat_flux
fix_initialcondition_gradient_heat calls update_parameters_heat
fix_initialcondition calls fix_initialcondition_gradient_heat