Update_Parameters_Heat – FTDSS
Update_Parameters_Heat Subroutine
24 statements
Source File
public subroutine Update_Parameters_Heat(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Calls
Called by
Contents
Source Code
Update_Parameters_Heat
Source Code
    subroutine Update_Parameters_Heat(Solver)
        implicit none
        type(SolverInfo), intent(inout) :: Solver
        call Update_theta(Solver)
        call Update_Variables_Geometric (Solver%Heat%Variables%lambda%pre(:), Solver%Heat%Constants%ThermalConductivity, Solver%Si%pre, Solver%Heat%Constants%Porosity, Solver%Flags)
        call Update_Variables_Arithmetic(Solver%Heat%Variables%rho%pre(:),    Solver%Heat%Constants%Density,             Solver%Si%pre, Solver%Heat%Constants%Porosity, Solver%Flags)
        call Update_Variables_Arithmetic(Solver%Heat%Variables%Cp%pre(:),     Solver%Heat%Constants%HeatCapacity,        Solver%Si%pre, Solver%Heat%Constants%Porosity, Solver%Flags)
        call Update_Variables_Arithmetic(Solver%Heat%Variables%Cs%pre(:),     Solver%Heat%Constants%SpecificHeat,        Solver%Si%pre, Solver%Heat%Constants%Porosity, Solver%Flags)
        if (Solver%Flags%isGCC) then
            call Update_Cpa_GCC(Solver)
        else if (Solver%Flags%isPower) then
            call Update_Cpa_Power(Solver)
        end if
        if (Solver%Flags%isGCC .or. Solver%Flags%isPower) then
            call Update_Phase(Solver)
            call Update_Cadiv(Solver)
        end if
        if (Solver%isWater) then
            call Update_Gradient(Solver, Solver%P%pre(:), Solver%Water%Variables%hGrad)
            call Update_Flux(Solver%Water%Variables%wFlux, Solver%Water%Variables%Klh%pre(:), Solver%Water%Variables%hGrad)
            call Update_Gradient(Solver, Solver%T%pre(:), Solver%Heat%Variables%TGrad)
            ! print*,Solver%Heat%Constants%HeatCapacity%water
            ! print*,Solver%Water%Variables%wFlux%x(1:30)*Solver%T%pre(1:30)*Solver%Heat%Constants%HeatCapacity%water
            ! stop
            call Update_Heat_Flux(Solver%Heat%Variables%TFlux, Solver%Heat%Variables%lambda%pre(:), Solver%Heat%Variables%TGrad, Solver%Heat%Constants%HeatCapacity%water, Solver%Water%Variables%wFlux, Solver%T%pre)
        end if
    end subroutine Update_Parameters_Heat
Call graph
update_parameters_heat calls update_variables_geometric, update_phase, update_cpa_gcc, update_heat_flux, update_gradient, update_theta, update_variables_arithmetic, update_cpa_power, update_cadiv, update_flux
fix_initialcondition_gradient_heat calls update_parameters_heat
fix_initialcondition calls fix_initialcondition_gradient_heat