#:set REAL_KINDS = ['real32', 'real64', 'real128']

! (Suffix, Dimension, IsArray)
#:set RANKS = [ &
    ('scalar', '',       False), &
    ('rank1',  '(:)',    True),  &
    ('rank2',  '(:, :)', True)   &
    ]

!>
!> Provides generic functions to check for the presence of IEEE Not-a-Number (NaN)
!> values in real scalars and arrays of different ranks and kinds.
!>
module core_check_nan
    use, intrinsic :: iso_fortran_env, only: real32, real64, real128
    use, intrinsic :: ieee_arithmetic, only: ieee_is_nan
    implicit none
    private

    public :: has_nan

    !>
    !> A generic interface for checking for NaN values.
    !>
    interface has_nan
        #:for k in REAL_KINDS
            #:for r_name, _, _ in RANKS
                module procedure :: has_nan_${r_name}$_${k}$
            #:endfor
        #:endfor
    end interface

contains

    #:for k in REAL_KINDS
        ! ==========================================================================
        ! ${k}$ IMPLEMENTATIONS
        ! ==========================================================================
        #:for r_name, r_dim, is_array in RANKS
            !> Checks if a ${r_name}$ ${k}$ value contains NaN.
            logical function has_nan_${r_name}$_${k}$ (val)
                implicit none
                !> The value to check.
                real(${k}$), intent(in) :: val${r_dim}$

                #:if is_array
                    has_nan_${r_name}$_${k}$ = any(ieee_is_nan(val))
                #:else
                    has_nan_${r_name}$_${k}$ = ieee_is_nan(val)
                #:endif
            end function has_nan_${r_name}$_${k}$

        #:endfor
    #:endfor

end module core_check_nan
