Allocate_Vector – FTDSS
Allocate_Vector Interface
7 statements
Source File
public interface Allocate_Vector
Calls
Called by
Contents
Module Procedures
Check_Allocate_rank1_int32 Check_Allocate_rank1_real64 Check_Allocate_rank1_logical Check_Allocate_rank1_int32_specify Check_Allocate_rank1_real64_specify
Module Procedures
private subroutine Check_Allocate_rank1_int32(iar, ar_size)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout), allocatable :: iar(:)
integer(kind=int32), intent(in) :: ar_size
private subroutine Check_Allocate_rank1_real64(dar, ar_size)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout), allocatable :: dar(:)
integer(kind=int32), intent(in) :: ar_size
private subroutine Check_Allocate_rank1_logical(lar, ar_size)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), allocatable :: lar(:)
integer(kind=int32), intent(in) :: ar_size
private subroutine Check_Allocate_rank1_int32_specify(iar, ar_first, ar_last)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout), allocatable :: iar(:)
integer(kind=int32), intent(in) :: ar_first
integer(kind=int32), intent(in) :: ar_last
private subroutine Check_Allocate_rank1_real64_specify(dar, ar_first, ar_last)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout), allocatable :: dar(:)
integer(kind=int32), intent(in) :: ar_first
integer(kind=int32), intent(in) :: ar_last
Call graph
allocate_vector calls check_allocate_rank1_int32_specify, check_allocate_rank1_real64, check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
error_message calls mpi_finalize
output_constructor calls allocate_vector
allocate_bcinfo calls allocate_vector, allocate_int2d
allocate_dp2d calls allocate_vector
allocate_df calls allocate_vector
convert_crs calls allocate_vector
set_obs_coo_31 calls allocate_vector
set_boundary_condition_infomations calls allocate_vector
allocate_int2d calls allocate_vector
allocate_solver calls allocate_vector, allocate_dp2d, allocate_df
output calls output_constructor
heat_constructor calls set_boundary_condition_infomations
set_obs_coo calls set_obs_coo_31
heat calls heat_constructor