Allocate_Matrix – FTDSS
Allocate_Matrix Interface
4 statements
Source File
public interface Allocate_Matrix
Calls
Called by
Contents
Module Procedures
Check_Allocate_rank2_int32 Check_Allocate_rank2_real64
Module Procedures
private subroutine Check_Allocate_rank2_int32(imt, mt_size_1, mt_size_2)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout), allocatable :: imt(:,:)
integer(kind=int32), intent(in) :: mt_size_1
integer(kind=int32), intent(in) :: mt_size_2
private subroutine Check_Allocate_rank2_real64(dmt, mt_size_1, mt_size_2)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout), allocatable :: dmt(:,:)
integer(kind=int32), intent(in) :: mt_size_1
integer(kind=int32), intent(in) :: mt_size_2
Call graph
allocate_matrix calls check_allocate_rank2_int32, check_allocate_rank2_real64
check_allocate_rank2_int32 calls error_message
check_allocate_rank2_real64 calls error_message
error_message calls mpi_finalize
calc_gm_time_trm_f calls allocate_matrix
allocate_solver calls allocate_matrix
solve_initialize_bicgstab calls allocate_matrix
set_obs_coo_31 calls allocate_matrix
ils calls solve_initialize_bicgstab
set_obs_coo calls set_obs_coo_31