Heat – FTDSS
Heat Interface
3 statements
Source File
public interface Heat
Calls
Contents
Module Procedures
Heat_Constructor
Module Procedures
private function Heat_Constructor(Structure_Input)
Arguments
Type Intent Optional Attributes Name
type(Input), intent(in) :: Structure_Input
Return Value type(Heat)
Call graph
heat calls heat_constructor
heat_constructor calls set_geometory_infomation, hcf, array_hcf, set_boundary_condition_infomations
hcf calls hcf_constructor
set_boundary_condition_infomations calls count_if, condition_in_boundarycondition, condition_heat, allocate_vector
count_if calls count_if_int32, count_if_int32_array
allocate_vector calls check_allocate_rank1_real64, check_allocate_rank1_int32_specify, check_allocate_rank1_int32, check_allocate_rank1_logical, check_allocate_rank1_real64_specify
check_allocate_rank1_real64 calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
error_message calls mpi_finalize