ILS – FTDSS
ILS Interface
3 statements
Source File
public interface ILS
Calls
Contents
Module Procedures
Solve_Initialize_BiCGStab
Module Procedures
private function Solve_Initialize_BiCGStab(Solver, MCRS)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(in) :: Solver
type(CRS), intent(in) :: MCRS
Return Value type(ILS)
Call graph
ils calls solve_initialize_bicgstab
solve_initialize_bicgstab calls allocate_matrix, duplicate_crs
allocate_matrix calls check_allocate_rank2_int32, check_allocate_rank2_real64
check_allocate_rank2_int32 calls error_message
check_allocate_rank2_real64 calls error_message
error_message calls mpi_finalize