Output – FTDSS
Output Interface
3 statements
Source File
public interface Output
Calls
Contents
Module Procedures
Output_Constructor
Module Procedures
private function Output_Constructor(Inputs)
Arguments
Type Intent Optional Attributes Name
type(Input), intent(in) :: Inputs
Return Value type(Output)
Call graph
output calls output_constructor
output_constructor calls inout_setprojectpath_getprojectpath, allocate_vector, set_output_flag
inout_setprojectpath_getprojectpath calls inout_setprojectpath_setprojectpath
allocate_vector calls check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32, check_allocate_rank1_int32_specify, check_allocate_rank1_real64
inout_setprojectpath_setprojectpath calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
error_message calls mpi_finalize