Set_Point – FTDSS
Set_Point Interface
3 statements
Source File
public interface Set_Point
Calls
Called by
Contents
Module Procedures
Set_Point_31
Module Procedures
private subroutine Set_Point_31(Geometry, triangle_index, p1, p2, p3)
Arguments
Type Intent Optional Attributes Name
type(Geometry2d), intent(in) :: Geometry
integer(kind=int32), intent(in) :: triangle_index
type(Vector2D), intent(inout) :: p1
type(Vector2D), intent(inout) :: p2
type(Vector2D), intent(inout) :: p3
Call graph
set_point calls set_point_31
set_point_31 calls error_message
error_message calls mpi_finalize
calc_area_31 calls set_point
calc_shape_31 calls set_point
set_obs_coo_31 calls set_point
calc_area calls calc_area_31
calc_shape calls calc_shape_31
set_obs_coo calls set_obs_coo_31