Set_Obs_COO – FTDSS
Set_Obs_COO Interface
3 statements
Source File
public interface Set_Obs_COO
Calls
Contents
Module Procedures
Set_Obs_COO_31
Module Procedures
private subroutine Set_Obs_COO_31(Solver)
Arguments
Type Intent Optional Attributes Name
type(SolverInfo), intent(inout) :: Solver
Call graph
set_obs_coo calls set_obs_coo_31
set_obs_coo_31 calls allocate_vector, is_in_triangle, set_point, allocate_matrix
allocate_vector calls check_allocate_rank1_int32_specify, check_allocate_rank1_real64, check_allocate_rank1_logical, check_allocate_rank1_real64_specify, check_allocate_rank1_int32
set_point calls set_point_31
allocate_matrix calls check_allocate_rank2_real64, check_allocate_rank2_int32
check_allocate_rank1_int32_specify calls error_message
check_allocate_rank1_real64 calls error_message
set_point_31 calls error_message
check_allocate_rank2_real64 calls error_message
check_allocate_rank1_logical calls error_message
check_allocate_rank1_real64_specify calls error_message
check_allocate_rank1_int32 calls error_message
check_allocate_rank2_int32 calls error_message
error_message calls mpi_finalize