#:mute
    #:set PRECISION_BITS = { &
        'integer': [8, 16, 32, 64], &
        'real':    [32, 64, 128], &
        'logical': [1, 4, 8] &
        }

    #:set KINDS = { &
        'integer': ["int{}".format(b) for b in PRECISION_BITS['integer']], &
        'real':    ["real{}".format(b) for b in PRECISION_BITS['real']], &
        'logical': ["{}".format(b)    for b in PRECISION_BITS['logical']] &
        }

    #:set TYPES = { &
        'integer': ["integer({})".format(k) for k in KINDS['integer']], &
        'real':    ["real({})".format(k)    for k in KINDS['real']], &
        'logical': ["logical({})".format(k) for k in KINDS['logical']] &
        }

    #:def rank_suffix(rank)
        ${"({0})".format(":" + ",:" * (rank - 1)) if rank > 0 else ""}$
    #:enddef
#:endmute
