# :mute
# ! number of bits of integer type
# :set INTEGER_BITS = [8, 16, 32, 64]

# ! integer kinds
# :set INTEGER_KINDS = ["int{}".format(bits) for bits in INTEGER_BITS]

# ! integer types
# :set INTEGER_TYPES = ["integer({})".format(kind) for kind in INTEGER_KINDS]

# ! nubmer of bits of real type
# :set REAL_BITS = [32, 64]

# ! real kinds
# :set REAL_KINDS = ["real{}".format(bits) for bits in REAL_BITS]

# ! real types
# :set REAL_TYPES = ["real({})".format(kind) for kind in REAL_KINDS]

# :endmute