#:include "constants.fypp"

!>
!> Module defining various constant ID groups
!>
module core_constants_error
    use, intrinsic :: iso_fortran_env
    use :: stdlib_strings, only:strip
    use :: stdlib_ascii, only:to_lower
    use :: core_constants_base, only:type_constant_error
    implicit none
    private

    ! --------------------------------------------------------------------------
    ! Error Constants Definition (using type_constant_error)
    ! --------------------------------------------------------------------------

    !> ${ERROR_CODES['description']}$
    type :: ${ERROR_CODES['type_name']}$
        !> Group name
        character(len=64) :: group = "${ERROR_CODES['category']}$"
        #:for item in ERROR_CODES['items']
        !> ${item[0]}$ error (ID: ${item[1]}$)
        !> Message: ${item[2]}$
        type(type_constant_error) :: ${item[0]}$ = type_constant_error("${ERROR_CODES['category']}$", &
                                                                    "${item[0]}$", &
                                                                    ${item[1]}$, &
                                                                    "${item[2]}$" &
                                                                    )
        #:endfor

        !> Number of error codes
        integer(int32) :: NUM_ID = ${len(ERROR_CODES['items'])}$

    contains
        ! Type-Bound Procedures for access and validation
        procedure, public, pass(self) :: to_id => to_id_${ERROR_CODES['suffix']}$
        procedure, public, pass(self) :: to_name => to_name_${ERROR_CODES['suffix']}$

        procedure, private, pass(self) :: to_object_from_id => to_object_from_id_${ERROR_CODES['suffix']}$
        procedure, private, pass(self) :: to_object_from_name => to_object_from_name_${ERROR_CODES['suffix']}$
        generic, public :: to_object => to_object_from_id, to_object_from_name

        procedure, public, pass(self) :: is_valid => is_valid_${ERROR_CODES['suffix']}$
    end type ${ERROR_CODES['type_name']}$

    !> Global instance of error constants
    type(${ERROR_CODES['type_name']}$), parameter, public :: ${ERROR_CODES['obj_name']}$ = ${ERROR_CODES['type_name']}$ ()

    contains

    ! --------------------------------------------------------------------------
    ! Implementation of Procedures
    ! --------------------------------------------------------------------------

    !> Get ID from name (Pure)
    pure function to_id_${ERROR_CODES['suffix']}$(self, name) result(id)
        implicit none
        class(${ERROR_CODES['type_name']}$), intent(in) :: self
        character(*), intent(in) :: name
        integer(int32) :: id

        type(type_constant_error) :: obj

        obj = self%to_object(name)
        id = obj%ID
    end function to_id_${ERROR_CODES['suffix']}$

    !> Get Name from ID (Pure)
    pure function to_name_${ERROR_CODES['suffix']}$(self, id) result(res)
        implicit none
        class(${ERROR_CODES['type_name']}$), intent(in) :: self
        integer(int32), intent(in) :: id
        character(len=64) :: res
        type(type_constant_error) :: obj

        obj = self%to_object(id)
        res = obj%name
    end function to_name_${ERROR_CODES['suffix']}$

    !> Get Error Object from ID (Pure)
    pure function to_object_from_id_${ERROR_CODES['suffix']}$ (self, id) result(res)
        implicit none
        class(${ERROR_CODES['type_name']}$), intent(in) :: self
        integer(int32), intent(in) :: id
        type(type_constant_error) :: res

        select case (id)
            #:for item in ERROR_CODES['items']
                case (${item[1]}$)
                res = self%${item[0]}$
            #:endfor
        case default
            ! Return an invalid/unknown error object
            res = type_constant_error("${ERROR_CODES['category']}$", "UNKNOWN", -1, "Unknown Error ID")
        end select
    end function to_object_from_id_${ERROR_CODES['suffix']}$

    !> Get Error Object from Name (Pure)
    pure function to_object_from_name_${ERROR_CODES['suffix']}$ (self, name) result(res)
        implicit none
        class(${ERROR_CODES['type_name']}$), intent(in) :: self
        character(*), intent(in) :: name
        type(type_constant_error) :: res

        select case (strip(name))
        #:for item in ERROR_CODES['items']
        case ("${item[0]}$")
            res = self%${item[0]}$
        #:endfor
        case default
            res = type_constant_error("${ERROR_CODES['category']}$", "UNKNOWN", -1, "Unknown Error Name")
        end select
    end function to_object_from_name_${ERROR_CODES['suffix']}$

    !> Check if an error ID is valid (Pure)
    pure function is_valid_${ERROR_CODES['suffix']}$ (self, id) result(res)
        implicit none
        class(${ERROR_CODES['type_name']}$), intent(in) :: self
        integer(int32), intent(in) :: id
        logical :: res
        type(type_constant_error) :: obj

        obj = self%to_object(id)
        res = (obj%ID /= -1)
    end function is_valid_${ERROR_CODES['suffix']}$

end module core_constants_error
