name: docs

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy-on-push
      run: |
        echo "DEPLOY_BRANCH=${{ github.ref }}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies Ubuntu
      run: |
        sudo apt-get update
        sudo apt install -y gfortran python3-dev graphviz
        python -m pip install ford markdown==3.3.4

    - name: Install dependencies
      run: pip install ford

    - name: Build Documentation
      run: ford api-docs-ford-settings.md

    - name: Deploy API Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.6
      if: ${{ github.event_name == 'push' && contains(github.ref, 'main') }}
      with:
        branch: gh-pages
        folder: docs/api-docs
        single-commit: true
