name: Build and Deploy Documentations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      FC: gfortran
      GCC_V: 12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran-${GCC_V} python3-dev graphviz

      - name: Upgrade pip & Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          # 最新版の Ford を強制的にインストール
          python3 -m pip install --upgrade ford
          # Markdown はプロジェクト要件に合わせて固定
          python3 -m pip install markdown==3.3.4

      - name: Verify Ford Version
        run: ford --version

      - name: Build Developer Documentation
        run: ford api-docs-ford-settings.md

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./docs/api-docs
          if-no-files-found: error

      - name: Deploy API Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: ./docs/api-docs
