name: Build and Deploy Documentations

on: [push, pull_request]

jobs:
  documentation:
    runs-on: ubuntu-22.04

    env:
      FC: gfortran
      GCC_V: 12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies Ubuntu
      run: |
        sudo apt-get update
        sudo apt install -y gfortran-${GCC_V} python3-dev graphviz
        sudo pip install ford markdown==3.3.4

    - name: Build Developer Documentation
      run: |
        ford api-docs-ford-settings.md --output ./docs/api-docs

    - name: Upload Documentation
      uses: actions/upload-artifact@v３
      with:
        name: documentation
        path: ./docs/api-docs
        if-no-files-found: error

    - name: Deploy API Documentation
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: ./docs/api-docs